In [210]:
import pandas as pd
import datetime
import sqlite3
import pymysql
import pandas.io.sql as psql
from datetime import datetime as dt
import numpy as np
import pandas.tseries.offsets as offsets
# # import sqlalchemy as sqa

# import matplotlib.pyplot as plt
import python_ss.python_ss as ps
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json

import os
import ast
import db_dtypes
from google.cloud import bigquery
from google.oauth2 import service_account
from google.cloud import secretmanager

import socket
import python_ss.python_ss as ps

In [211]:
def access_secret_version(project_id, secret_id, version_id='latest'):
    client = secretmanager.SecretManagerServiceClient()

    name = f"projects/{project_id}/secrets/{secret_id}/versions/{version_id}"
    response = client.access_secret_version(request={"name": name})
    payload = response.payload.data.decode("UTF-8")
    return ast.literal_eval(payload)

In [212]:
# 上記関数を実行するコードが記載されています。こちらもそのままお使いください。
credentials = service_account.Credentials.from_service_account_info(
  access_secret_version('temp-for-sandbox', 'TEMP_CREDENTIAL_KEY'),
  scopes=["https://www.googleapis.com/auth/cloud-platform"],)

z:\Users\suehara\Documents\python\analysis\.venv\Lib\site-packages\google\auth\_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

In [213]:
# 上記関数を実行するコードが記載されています。こちらもそのままお使いください。
credentials = service_account.Credentials.from_service_account_info(
access_secret_version('r-group-bigdata', 'CREDENTIALS_SECRET_KEY_WORKER'),
scopes=["https://www.googleapis.com/auth/cloud-platform"],)

In [214]:
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', None)

## 広告情報取得

In [215]:
#最後のIDを取得する
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly',
          'https://www.googleapis.com/auth/spreadsheets']
json_path = r"Z:\Users\suehara\Documents\python\analysis\python_ss\credentials.json"
service = ps.get_auth(SCOPES,json_path)
SPREADSHEET_ID = '14vXxjcdlyY463QjrtEnCw7pJ0oLStXZD8Q42IdW2Zd4'
Sheet_NAME = '候補者マスタ!A'
Sheet_row = ":M"
RANGE_NAME = Sheet_NAME+Sheet_row
adinfo = ps.get_ss(SPREADSHEET_ID,RANGE_NAME,service)

In [216]:
adinfoA = adinfo.copy()

In [217]:
adinfoA.replace([np.inf, -np.inf], np.nan, inplace=True)
adinfoA.fillna('', inplace=True)
adinfoA = adinfoA.values.tolist()

In [218]:
#【主要媒体別】成約単価管理表【NEO】にコピペ
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly',
          'https://www.googleapis.com/auth/spreadsheets']
json_path = r"Z:\Users\suehara\Documents\python\analysis\python_ss\credentials.json"
service = ps.get_auth(SCOPES,json_path)
SPREADSHEET_ID = '1Mvqe8nLhdiT9acCMA4cP-4MH5X4GmYPiC9OSqHTEHtk'
service = ps.get_auth(SCOPES, json_path)
Sheet_NAME = 'user!A'
Sheet_row = '2'
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,adinfoA,service)

In [219]:
adinfoA

[['1070',
  '2016/09/17',
  'ロンザン',
  '2020/05/20',
  'ZOOM',
  '',
  '',
  '',
  '',
  '',
  '',
  '49',
  '部長クラス'],
 ['2748',
  '2017/02/06',
  'ロンザン',
  '2017/02/06',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '59',
  '役員クラス'],
 ['7024',
  '2017/08/07',
  'ロンザン',
  '2017/08/07',
  '',
  '',
  'google_SHIMEI / cpc',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '55',
  'リーダークラス'],
 ['8539',
  '2017/09/15',
  'レイノス',
  '2017/09/15',
  '',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '35',
  'リーダークラス'],
 ['9502',
  '2017/10/05',
  'レイノス',
  '2017/10/05',
  '0',
  '',
  'yahoo_Ten / cpc_CA',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '45',
  '役員クラス'],
 ['11522',
  '2017/11/20',
  'ロンザン',
  '2017/11/20',
  '0',
  '',
  'Indeed / cpc',
  'Indeed',
  '(not set)',
  '(not set)',
  '',
  '56',
  '一般クラス'],
 ['12216',
  '2017/12/13',
  'レイノス',
  '2017/12/13',
  '0',
  '',
  'google / organic',
  '(not set)',
  '(not set)',
  '(not provided)',
  '',
  '46',
  '部長クラス'],
 ['12406',
  '2017/12/20',
  'レイノス',
  '2017/12/20',
  '0',
  '',
  'google_Saiyo / cpc_Area',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '',
  ''],
 ['12511',
  '2017/12/24',
  'レイノス',
  '2017/12/24',
  '0',
  '',
  'google_Saiyo / cpc_CA',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '36',
  '課長クラス'],
 ['12511',
  '2017/12/24',
  'レイノス',
  '2017/12/24',
  '0',
  '',
  'google_Saiyo / cpc_CA',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '36',
  '課長クラス'],
 ['13590',
  '2018/01/24',
  'ロンザン',
  '2018/01/24',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '51',
  '部長クラス'],
 ['13663',
  '2018/01/25',
  'ロンザン',
  '2018/01/25',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '',
  '部長クラス'],
 ['15374',
  '2018/02/25',
  'レイノス',
  '2018/02/25',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '',
  '課長クラス'],
 ['15687',
  '2018/03/01',
  'レイノス',
  '2018/03/01',
  '0',
  '',
  'yahoo_Saiyo_senior / cpc_Saiyo_age',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '',
  '課長クラス'],
 ['17233',
  '2018/04/01',
  'ロンザン',
  '2018/04/01',
  '0',
  '',
  'Affiliate_AT / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '55',
  '課長クラス'],
 ['18073',
  '2018/04/20',
  'レイノス',
  '2018/04/20',
  '0',
  '',
  'google_Shimei / cpc_Shimei_E',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '39',
  '役員クラス'],
 ['18982',
  '2018/05/09',
  '',
  '',
  '0',
  '',
  'YDN_RT / display_All_R',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '47',
  '役員クラス'],
 ['19496',
  '2018/05/17',
  'レイノス',
  '2018/05/17',
  '0',
  '',
  'google / cpc',
  '転職_掛け合わせ_ミドル_SN',
  'シニア世代の求人情報',
  '転職 経営者',
  '',
  '50',
  '部長クラス'],
 ['19560',
  '2018/05/19',
  'ロンザン',
  '2018/05/19',
  '0',
  '',
  'smartnews_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '62',
  '役員クラス'],
 ['20241',
  '2018/05/29',
  'レイノス',
  '2018/05/29',
  '0',
  '',
  'Affiliate_AT / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '40',
  '課長クラス'],
 ['20561',
  '2018/06/03',
  'ロンザン',
  '2018/06/03',
  '0',
  '',
  'google / cpc',
  '採用_掛け合わせ_SN',
  '社長の右腕、経営幹部案件ご用意',
  '採用 キャリア',
  '',
  '51',
  'リーダークラス'],
 ['21468',
  '2018/06/17',
  'レイノス',
  '2018/06/17',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '42',
  '課長クラス'],
 ['21835',
  '2018/06/23',
  'ロンザン',
  '2018/06/23',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '59',
  '役職なし'],
 ['22861',
  '2018/07/08',
  'ロンザン',
  '2020/02/04',
  '対面',
  '',
  '(direct) / (none)',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '47',
  '課長クラス'],
 ['23336',
  '2018/07/15',
  'ロンザン',
  '2018/07/15',
  '0',
  '',
  '(direct) / (none)',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '60',
  '部長クラス'],
 ['23425',
  '2018/07/16',
  'ロンザン',
  '2018/07/16',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '56',
  '役員クラス'],
 ['23650',
  '2018/07/20',
  'レイノス',
  '2018/07/20',
  '0',
  '',
  'google / cpc',
  '転職_掛け合わせ_SN',
  '転職先は経営者で決める',
  '+転職 +ハイクラス',
  '',
  '33',
  'リーダークラス'],
 ['24734',
  '2018/08/06',
  'ロンザン',
  '2018/08/06',
  '0',
  '',
  '(direct) / (none)',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '51',
  '役員クラス'],
 ['25493',
  '2018/08/19',
  'ロンザン',
  '2018/08/19',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '53',
  '部長クラス'],
 ['26480',
  '2018/08/31',
  'ロンザン',
  '2018/08/31',
  '0',
  '',
  'google / organic',
  '(not set)',
  '(not set)',
  '(not provided)',
  '',
  '59',
  '部長クラス'],
 ['26710',
  '2018/09/02',
  'ロンザン',
  '2018/09/02',
  '0',
  '',
  'yahoo / cpc',
  '357176933',
  '(not set)',
  '転機',
  '',
  '59',
  '部長クラス'],
 ['27292',
  '2018/09/10',
  'レイノス',
  '2018/09/10',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '32',
  '主任・主査クラス'],
 ['27656',
  '2018/09/14',
  'レイノス',
  '2018/09/14',
  '0',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '44',
  '部長クラス'],
 ['27848',
  '2018/09/16',
  'ロンザン',
  '2018/09/16',
  '0',
  '',
  'bing / organic',
  '(not set)',
  '(not set)',
  '転機.com',
  '',
  '49',
  '部長クラス'],
 ['29317',
  '2018/10/09',
  'レイノス',
  '2018/10/09',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '40',
  '部長クラス'],
 ['30424',
  '2018/11/03',
  'レイノス',
  '2018/11/03',
  '0',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '40',
  '部長クラス'],
 ['31082',
  '2018/11/17',
  'ロンザン',
  '2018/11/17',
  '0',
  '',
  'yahoo / cpc',
  '1598314721',
  '(not set)',
  '転機',
  '',
  '60',
  '部長クラス'],
 ['31471',
  '2018/11/24',
  'ロンザン',
  '2018/11/24',
  '0',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '48',
  '部長クラス'],
 ['31861',
  '2018/12/02',
  'レイノス',
  '2018/12/02',
  '0',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '41',
  '課長クラス'],
 ['32182',
  '2018/12/08',
  'ロンザン',
  '2018/12/08',
  '0',
  '',
  'google / cpc',
  '【近畿】リマケ_年収上位_DN（カテゴリーA）',
  '会社を創るメンバーになる',
  '(Remarketing/Content targeting)',
  '',
  '59',
  '部長クラス'],
 ['32424',
  '2018/12/14',
  'ロンザン',
  '2018/12/14',
  '0',
  '',
  'fb_ad_top / display',
  'fb-adset4',
  '(not set)',
  '(not set)',
  '',
  '56',
  '部長クラス'],
 ['32788',
  '2018/12/22',
  'レイノス',
  '2018/12/22',
  '0',
  '',
  'yahoo / organic',
  '(not set)',
  '(not set)',
  '(not provided)',
  '',
  '51',
  '部長クラス'],
 ['32857',
  '2018/12/23',
  'レイノス',
  '2018/12/23',
  '0',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '46',
  '課長クラス'],
 ['32859',
  '2018/12/23',
  'レイノス',
  '2018/12/23',
  '0',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '49',
  '課長クラス'],
 ['33047',
  '2018/12/29',
  'レイノス',
  '2018/12/29',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '45',
  '部長クラス'],
 ['33125',
  '2019/01/01',
  'ロンザン',
  '2019/01/01',
  '0',
  '',
  'Indeed / cpc',
  'indeed4-2',
  '(not set)',
  '(not set)',
  '',
  '56',
  '部長クラス'],
 ['33207',
  '2019/01/03',
  'ロンザン',
  '2019/01/03',
  '対面',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '56',
  '部長クラス'],
 ['33429',
  '2019/01/06',
  'レイノス',
  '2019/01/06',
  '0',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '34',
  '主任・主査クラス'],
 ['33566',
  '2019/01/09',
  'レイノス',
  'コールセンター',
  'TV会議',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '53',
  '部長クラス'],
 ['33611',
  '2019/01/10',
  'ロンザン',
  '2019/10/28',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '47',
  '社長・会長クラス'],
 ['33792',
  '2019/01/15',
  'ロンザン',
  '2019/01/15',
  '対面',
  '',
  'fb_ad_top / display',
  'fb-adset4',
  '(not set)',
  '(not set)',
  '',
  '57',
  '部長クラス'],
 ['34115',
  '2019/01/21',
  'レイノス',
  '2019/01/21',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '55',
  '部長クラス'],
 ['34298',
  '2019/01/23',
  'レイノス',
  'コールセンター',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '45',
  '課長クラス'],
 ['34308',
  '2019/01/23',
  'ロンザン',
  '2019/08/09',
  'TV会議',
  '',
  'yahoo / organic',
  '(not set)',
  '(not set)',
  '(not provided)',
  '',
  '54',
  '部長クラス'],
 ['34481',
  '2019/01/26',
  'レイノス',
  '2019/01/26',
  '対面',
  '',
  'google / cpc',
  '【全国】指名_年齢不明_SN（カテゴリーA）',
  '転職先は経営者で決める',
  '転機',
  '',
  '43',
  '部長クラス'],
 ['34487',
  '2019/01/26',
  'ロンザン',
  '2019/01/26',
  'TV会議',
  '',
  'google / cpc',
  '【全国】年収上位_SN（カテゴリーA）',
  '社長の右腕、経営幹部案件ご用意',
  '求人 経営者',
  '',
  '66',
  '部長クラス'],
 ['34612',
  '2019/01/28',
  'ロンザン',
  'コールセンター',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '52',
  '部長クラス'],
 ['34863',
  '2019/02/02',
  'ロンザン',
  '2019/02/02',
  '対面',
  '',
  'google / cpc',
  '【全国】指名_年収上位_SN（カテゴリーA）',
  '【逆求人】特別オファーが届く',
  '転機',
  '',
  '56',
  '部長クラス'],
 ['35127',
  '2019/02/06',
  'レイノス',
  '2019/02/06',
  '対面',
  '',
  'google / cpc',
  '【全国】ミドル_SN（カテゴリーB）',
  '社長の右腕、経営幹部案件ご用意',
  '転職 ハイクラス',
  '',
  '47',
  '役員クラス'],
 ['35136',
  '2019/02/06',
  'レイノス',
  '2019/02/06',
  '対面',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '48',
  '部長クラス'],
 ['35189',
  '2019/02/07',
  'ロンザン',
  '2019/02/07',
  'TV会議',
  '',
  'yahoo / cpc',
  '1598314751',
  '(not set)',
  '転機',
  '',
  '58',
  '部長クラス'],
 ['35391',
  '2019/02/10',
  'ロンザン',
  'コールセンター',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '50',
  '社長・会長クラス'],
 ['35522',
  '2019/02/12',
  'ロンザン',
  '2019/02/12',
  'TV会議',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '56',
  '課長クラス'],
 ['35851',
  '2019/02/19',
  'レイノス',
  '2019/02/19',
  'ZOOM',
  '',
  'fb_ad_top / display',
  'fb-adset6',
  '(not set)',
  '(not set)',
  '',
  '42',
  '部長クラス'],
 ['35887',
  '2019/02/19',
  'レイノス',
  '2019/02/19',
  '対面',
  '',
  'google / cpc',
  '【全国】年齢不明_SN（カテゴリーA）',
  '社長の右腕、経営幹部案件ご用意',
  '転職 幹部',
  '',
  '32',
  '部長クラス'],
 ['35971',
  '2019/02/21',
  'ロンザン',
  '2019/02/21',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '57',
  '部長クラス'],
 ['36037',
  '2019/02/23',
  'ロンザン',
  '2019/11/27',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '51',
  '部長クラス'],
 ['36167',
  '2019/02/26',
  'レイノス',
  '2019/12/18',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '44',
  '主任・主査クラス'],
 ['36173',
  '2019/02/26',
  'レイノス',
  '2019/02/26',
  '対面',
  '',
  'google / cpc',
  '【全国】ミドル_SN（カテゴリーB）',
  'CxOとして事業を牽引する',
  '転職 キャリア',
  '',
  '50',
  '役員クラス'],
 ['36212',
  '2019/02/27',
  'レイノス',
  '2019/02/27',
  '対面',
  '',
  'google / cpc',
  '【全国】年齢不明_SN（カテゴリーA）',
  '社長の右腕、経営幹部案件ご用意',
  '転職 経営者',
  '',
  '50',
  '役員クラス'],
 ['36307',
  '2019/02/28',
  'ロンザン',
  '2019/02/28',
  'Skype',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '57',
  '役員クラス'],
 ['36428',
  '2019/03/03',
  'ロンザン',
  '2019/03/03',
  '対面',
  '',
  'google / cpc',
  '【全国】指名_年収上位_SN（カテゴリーA）',
  '転職先は経営者で決める',
  '転機',
  '',
  '55',
  '部長クラス'],
 ['36951',
  '2019/03/14',
  'ロンザン',
  '2019/03/14',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '55',
  '部長クラス'],
 ['37111',
  '2019/03/18',
  'レイノス',
  '2019/03/18',
  'ZOOM',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '47',
  '部長クラス'],
 ['37154',
  '2019/03/19',
  'レイノス',
  '2019/03/19',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '50',
  '役員クラス'],
 ['37413',
  '2019/03/24',
  'ロンザン',
  '2019/03/24',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '51',
  '課長クラス'],
 ['37468',
  '2019/03/25',
  'ロンザン',
  '2019/03/25',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '60',
  '役員クラス'],
 ['37468',
  '2019/03/25',
  'ロンザン',
  '2019/03/25',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '60',
  '役員クラス'],
 ['37826',
  '2019/04/02',
  'ロンザン',
  '2019/04/02',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '52',
  '部長クラス'],
 ['37991',
  '2019/04/05',
  'ロンザン',
  '2019/04/05',
  '対面',
  '',
  'google / cpc',
  '【東海】年収上位_SN（カテゴリーA）',
  '社長の右腕、経営幹部案件ご用意',
  '転職 キャリア',
  '',
  '52',
  '部長クラス'],
 ['37993',
  '2019/04/05',
  'ロンザン',
  '2019/04/05',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '55',
  '課長クラス'],
 ['38061',
  '2019/04/07',
  'ロンザン',
  '2019/04/07',
  'TV会議',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '49',
  '社長・会長クラス'],
 ['38242',
  '2019/04/10',
  'ロンザン',
  '2019/04/10',
  '対面',
  '',
  '(direct) / (none)',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '60',
  '役職なし'],
 ['38383',
  '2019/04/13',
  'レイノス',
  '2019/04/13',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '51',
  '役員クラス'],
 ['38446',
  '2019/04/14',
  'ロンザン',
  '2019/04/14',
  '電話',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '53',
  '部長クラス'],
 ['38538',
  '2019/04/15',
  'レイノス',
  '2019/04/15',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '47',
  '課長クラス'],
 ['39036',
  '2019/04/24',
  'ロンザン',
  '2019/04/24',
  'TV会議',
  '',
  'google / cpc',
  '【全国】シニア_SN（カテゴリーB）',
  '定年前にキャリアの見直しを',
  '定年退職 キャリア',
  '',
  '55',
  '役員クラス'],
 ['39235',
  '2019/04/29',
  'レイノス',
  '2019/04/29',
  '対面',
  '',
  'yahoo / cpc',
  '1593591720',
  '(not set)',
  '求人 キャリア',
  '',
  '45',
  '課長クラス'],
 ['39401',
  '2019/05/02',
  'ロンザン',
  '2019/05/02',
  '対面',
  '',
  'zeals_ad / chat_cpf',
  'shot',
  '(not set)',
  '(not set)',
  '(not set)',
  '52',
  '役員クラス'],
 ['39920',
  '2019/05/14',
  'ロンザン',
  '2019/05/14',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '54',
  '課長クラス'],
 ['40126',
  '2019/05/19',
  'ロンザン',
  '2019/10/29',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '49',
  '役員クラス'],
 ['40237',
  '2019/05/22',
  'ロンザン',
  '2019/05/22',
  '対面',
  '',
  'google / cpc',
  '【全国】年齢不明_SN（カテゴリーA）',
  '社長の右腕、経営幹部案件ご用意',
  '転職 マネージャー',
  '',
  '63',
  '顧問'],
 ['40238',
  '2019/05/22',
  'ロンザン',
  '2019/05/22',
  '対面',
  '',
  'google / cpc',
  '【全国】シニア_SN（カテゴリーB）',
  '定年前にキャリアの見直しを',
  '定年 キャリア',
  '',
  '59',
  '部長クラス'],
 ['40266',
  '2019/05/23',
  'ロンザン',
  '2019/05/23',
  'ZOOM',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '63',
  '部長クラス'],
 ['40322',
  '2019/05/24',
  'ロンザン',
  '2019/05/24',
  '対面',
  '',
  'Indeed / organic',
  'Indeed',
  '(not set)',
  '(not set)',
  '',
  '62',
  '顧問'],
 ['40425',
  '2019/05/27',
  'ロンザン',
  '2019/05/27',
  '対面',
  '',
  '(direct) / (none)',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '55',
  '課長クラス'],
 ['40506',
  '2019/05/28',
  'ロンザン',
  '2019/05/28',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '50',
  '社長・会長クラス'],
 ['40566',
  '2019/05/29',
  'レイノス',
  '2019/05/29',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '49',
  '部長クラス'],
 ['40640',
  '2019/05/30',
  'レイノス',
  '2019/05/30',
  '対面',
  '',
  'google / cpc',
  '【全国】年齢不明_SN（カテゴリーA）',
  'スカウトを受けて転職',
  'オファー キャリア',
  '',
  '42',
  '役員クラス'],
 ['40717',
  '2019/06/01',
  'ロンザン',
  '2019/06/01',
  '対面',
  '',
  'google / cpc',
  '【全国】シニア_SN（カテゴリーB）',
  '社長の右腕、経営幹部案件ご用意',
  '転職 60歳',
  '',
  '61',
  '部長クラス'],
 ['40949',
  '2019/06/05',
  'ロンザン',
  '2019/06/05',
  'TV会議',
  '',
  'google / cpc',
  '【近畿】ミドル_SN（カテゴリーB）',
  '社長の右腕、経営幹部案件ご用意',
  '求人 経営者',
  '',
  '58',
  '部長クラス'],
 ['41036',
  '2019/06/07',
  'ロンザン',
  '2019/06/07',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '54',
  '部長クラス'],
 ['41204',
  '2019/06/11',
  'レイノス',
  '2019/06/11',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '46',
  '課長クラス'],
 ['41240',
  '2019/06/12',
  'ロンザン',
  '2019/06/12',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '59',
  '課長クラス'],
 ['41279',
  '2019/06/12',
  'ロンザン',
  '2019/08/09',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '82',
  '部長クラス'],
 ['41328',
  '2019/06/13',
  'ロンザン',
  '2019/06/13',
  'ZOOM',
  '',
  'google / cpc',
  '【全国】シニア_SN（カテゴリーB）',
  '社長の右腕として採用',
  '求人 キャリア',
  '',
  '59',
  '部長クラス'],
 ['41337',
  '2019/06/13',
  'ロンザン',
  '2019/08/07',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset4',
  '(not set)',
  '(not set)',
  '',
  '51',
  '部長クラス'],
 ['41432',
  '2019/06/15',
  'ロンザン',
  '2019/06/15',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '54',
  '部長クラス'],
 ['41437',
  '2019/06/15',
  'ロンザン',
  '2019/06/15',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '55',
  '役員クラス'],
 ['41555',
  '2019/06/17',
  'ロンザン',
  '2019/06/17',
  '対面',
  '',
  'google / cpc',
  '【全国】シニア_SN（カテゴリーB）',
  '特別オファーが届く',
  'ヘッドハンティング キャリア',
  '',
  '57',
  '部長クラス'],
 ['41851',
  '2019/06/23',
  'ロンザン',
  '2022/11/14',
  'ZOOM',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '52',
  '部長クラス'],
 ['41872',
  '2019/06/24',
  'ロンザン',
  '2019/06/24',
  '対面',
  '',
  'google / cpc',
  '【全国】指名_ミドル_SN（カテゴリーB）',
  '特別オファーが届く',
  '転機',
  '',
  '54',
  '課長クラス'],
 ['42146',
  '2019/06/30',
  'ロンザン',
  '2019/06/30',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '57',
  '部長クラス'],
 ['42184',
  '2019/06/30',
  'ロンザン',
  '2019/06/30',
  'ZOOM',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '50',
  '役職なし'],
 ['42272',
  '2019/07/02',
  'ロンザン',
  '2019/08/07',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '55',
  '部長クラス'],
 ['42460',
  '2019/07/06',
  'レイノス',
  '2019/07/06',
  '対面',
  '',
  'google / cpc',
  '【全国】ミドル_SN（カテゴリーB）',
  'CxOとして事業を牽引する',
  '中途採用 キャリア',
  '',
  '',
  ''],
 ['42556',
  '2019/07/08',
  'ロンザン',
  '2019/07/08',
  'TV会議',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '60',
  '部長クラス'],
 ['42754',
  '2019/07/12',
  'ロンザン',
  '2019/07/12',
  '対面',
  '',
  'shachomeikan.jp / referral',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '',
  ''],
 ['42959',
  '2019/07/17',
  'ロンザン',
  '2019/07/17',
  'TV会議',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '51',
  '部長クラス'],
 ['42991',
  '2019/07/18',
  'ロンザン',
  '2019/07/18',
  'TV会議',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '54',
  '社長・会長クラス'],
 ['43037',
  '2019/07/19',
  'ロンザン',
  '2019/07/19',
  '対面',
  '',
  'google / cpc',
  '【全国】SDC_シニア・その他統合_DN（カテゴリーB）',
  '(not set)',
  '(not set)',
  '',
  '55',
  '部長クラス'],
 ['43038',
  '2019/07/19',
  'ロンザン',
  '2019/12/26',
  '電話orTV会議',
  '',
  'yahoo / cpc',
  '1598314733',
  '(not set)',
  '転機',
  '',
  '58',
  '主任・主査クラス'],
 ['43088',
  '2019/07/20',
  'ロンザン',
  '2019/07/20',
  'ZOOM',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '51',
  '役員クラス'],
 ['43122',
  '2019/07/21',
  'レイノス',
  '2019/07/21',
  '対面',
  '',
  'google / cpc',
  '【近畿】指名_年収上位_SN（カテゴリーA）',
  '逆求人型転職は『転機』',
  '転機',
  '',
  '44',
  'リーダークラス'],
 ['43159',
  '2019/07/22',
  'ロンザン',
  '2019/07/22',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '53',
  'リーダークラス'],
 ['43358',
  '2019/07/28',
  'ロンザン',
  '2019/07/28',
  '電話',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '54',

In [220]:
#CAシートにコピペ
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly',
          'https://www.googleapis.com/auth/spreadsheets']
json_path = r"Z:\Users\suehara\Documents\python\analysis\python_ss\credentials.json"
service = ps.get_auth(SCOPES,json_path)
SPREADSHEET_ID = '1d1uYQMCIhJGMlUe4S8m56Bd_ZS4_V-FUEtPjUlgpn9Y'
service = ps.get_auth(SCOPES, json_path)
Sheet_NAME = 'user!A'
Sheet_row = '2'
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,adinfoA,service)

In [221]:
adinfoA

[['1070',
  '2016/09/17',
  'ロンザン',
  '2020/05/20',
  'ZOOM',
  '',
  '',
  '',
  '',
  '',
  '',
  '49',
  '部長クラス'],
 ['2748',
  '2017/02/06',
  'ロンザン',
  '2017/02/06',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '59',
  '役員クラス'],
 ['7024',
  '2017/08/07',
  'ロンザン',
  '2017/08/07',
  '',
  '',
  'google_SHIMEI / cpc',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '55',
  'リーダークラス'],
 ['8539',
  '2017/09/15',
  'レイノス',
  '2017/09/15',
  '',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '35',
  'リーダークラス'],
 ['9502',
  '2017/10/05',
  'レイノス',
  '2017/10/05',
  '0',
  '',
  'yahoo_Ten / cpc_CA',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '45',
  '役員クラス'],
 ['11522',
  '2017/11/20',
  'ロンザン',
  '2017/11/20',
  '0',
  '',
  'Indeed / cpc',
  'Indeed',
  '(not set)',
  '(not set)',
  '',
  '56',
  '一般クラス'],
 ['12216',
  '2017/12/13',
  'レイノス',
  '2017/12/13',
  '0',
  '',
  'google / organic',
  '(not set)',
  '(not set)',
  '(not provided)',
  '',
  '46',
  '部長クラス'],
 ['12406',
  '2017/12/20',
  'レイノス',
  '2017/12/20',
  '0',
  '',
  'google_Saiyo / cpc_Area',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '',
  ''],
 ['12511',
  '2017/12/24',
  'レイノス',
  '2017/12/24',
  '0',
  '',
  'google_Saiyo / cpc_CA',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '36',
  '課長クラス'],
 ['12511',
  '2017/12/24',
  'レイノス',
  '2017/12/24',
  '0',
  '',
  'google_Saiyo / cpc_CA',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '36',
  '課長クラス'],
 ['13590',
  '2018/01/24',
  'ロンザン',
  '2018/01/24',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '51',
  '部長クラス'],
 ['13663',
  '2018/01/25',
  'ロンザン',
  '2018/01/25',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '',
  '部長クラス'],
 ['15374',
  '2018/02/25',
  'レイノス',
  '2018/02/25',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '',
  '課長クラス'],
 ['15687',
  '2018/03/01',
  'レイノス',
  '2018/03/01',
  '0',
  '',
  'yahoo_Saiyo_senior / cpc_Saiyo_age',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '',
  '課長クラス'],
 ['17233',
  '2018/04/01',
  'ロンザン',
  '2018/04/01',
  '0',
  '',
  'Affiliate_AT / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '55',
  '課長クラス'],
 ['18073',
  '2018/04/20',
  'レイノス',
  '2018/04/20',
  '0',
  '',
  'google_Shimei / cpc_Shimei_E',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '39',
  '役員クラス'],
 ['18982',
  '2018/05/09',
  '',
  '',
  '0',
  '',
  'YDN_RT / display_All_R',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '47',
  '役員クラス'],
 ['19496',
  '2018/05/17',
  'レイノス',
  '2018/05/17',
  '0',
  '',
  'google / cpc',
  '転職_掛け合わせ_ミドル_SN',
  'シニア世代の求人情報',
  '転職 経営者',
  '',
  '50',
  '部長クラス'],
 ['19560',
  '2018/05/19',
  'ロンザン',
  '2018/05/19',
  '0',
  '',
  'smartnews_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '62',
  '役員クラス'],
 ['20241',
  '2018/05/29',
  'レイノス',
  '2018/05/29',
  '0',
  '',
  'Affiliate_AT / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '40',
  '課長クラス'],
 ['20561',
  '2018/06/03',
  'ロンザン',
  '2018/06/03',
  '0',
  '',
  'google / cpc',
  '採用_掛け合わせ_SN',
  '社長の右腕、経営幹部案件ご用意',
  '採用 キャリア',
  '',
  '51',
  'リーダークラス'],
 ['21468',
  '2018/06/17',
  'レイノス',
  '2018/06/17',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '42',
  '課長クラス'],
 ['21835',
  '2018/06/23',
  'ロンザン',
  '2018/06/23',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '59',
  '役職なし'],
 ['22861',
  '2018/07/08',
  'ロンザン',
  '2020/02/04',
  '対面',
  '',
  '(direct) / (none)',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '47',
  '課長クラス'],
 ['23336',
  '2018/07/15',
  'ロンザン',
  '2018/07/15',
  '0',
  '',
  '(direct) / (none)',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '60',
  '部長クラス'],
 ['23425',
  '2018/07/16',
  'ロンザン',
  '2018/07/16',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '56',
  '役員クラス'],
 ['23650',
  '2018/07/20',
  'レイノス',
  '2018/07/20',
  '0',
  '',
  'google / cpc',
  '転職_掛け合わせ_SN',
  '転職先は経営者で決める',
  '+転職 +ハイクラス',
  '',
  '33',
  'リーダークラス'],
 ['24734',
  '2018/08/06',
  'ロンザン',
  '2018/08/06',
  '0',
  '',
  '(direct) / (none)',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '51',
  '役員クラス'],
 ['25493',
  '2018/08/19',
  'ロンザン',
  '2018/08/19',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '53',
  '部長クラス'],
 ['26480',
  '2018/08/31',
  'ロンザン',
  '2018/08/31',
  '0',
  '',
  'google / organic',
  '(not set)',
  '(not set)',
  '(not provided)',
  '',
  '59',
  '部長クラス'],
 ['26710',
  '2018/09/02',
  'ロンザン',
  '2018/09/02',
  '0',
  '',
  'yahoo / cpc',
  '357176933',
  '(not set)',
  '転機',
  '',
  '59',
  '部長クラス'],
 ['27292',
  '2018/09/10',
  'レイノス',
  '2018/09/10',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '32',
  '主任・主査クラス'],
 ['27656',
  '2018/09/14',
  'レイノス',
  '2018/09/14',
  '0',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '44',
  '部長クラス'],
 ['27848',
  '2018/09/16',
  'ロンザン',
  '2018/09/16',
  '0',
  '',
  'bing / organic',
  '(not set)',
  '(not set)',
  '転機.com',
  '',
  '49',
  '部長クラス'],
 ['29317',
  '2018/10/09',
  'レイノス',
  '2018/10/09',
  '0',
  '',
  'fb_ad / display',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '40',
  '部長クラス'],
 ['30424',
  '2018/11/03',
  'レイノス',
  '2018/11/03',
  '0',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '40',
  '部長クラス'],
 ['31082',
  '2018/11/17',
  'ロンザン',
  '2018/11/17',
  '0',
  '',
  'yahoo / cpc',
  '1598314721',
  '(not set)',
  '転機',
  '',
  '60',
  '部長クラス'],
 ['31471',
  '2018/11/24',
  'ロンザン',
  '2018/11/24',
  '0',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '48',
  '部長クラス'],
 ['31861',
  '2018/12/02',
  'レイノス',
  '2018/12/02',
  '0',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '41',
  '課長クラス'],
 ['32182',
  '2018/12/08',
  'ロンザン',
  '2018/12/08',
  '0',
  '',
  'google / cpc',
  '【近畿】リマケ_年収上位_DN（カテゴリーA）',
  '会社を創るメンバーになる',
  '(Remarketing/Content targeting)',
  '',
  '59',
  '部長クラス'],
 ['32424',
  '2018/12/14',
  'ロンザン',
  '2018/12/14',
  '0',
  '',
  'fb_ad_top / display',
  'fb-adset4',
  '(not set)',
  '(not set)',
  '',
  '56',
  '部長クラス'],
 ['32788',
  '2018/12/22',
  'レイノス',
  '2018/12/22',
  '0',
  '',
  'yahoo / organic',
  '(not set)',
  '(not set)',
  '(not provided)',
  '',
  '51',
  '部長クラス'],
 ['32857',
  '2018/12/23',
  'レイノス',
  '2018/12/23',
  '0',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '46',
  '課長クラス'],
 ['32859',
  '2018/12/23',
  'レイノス',
  '2018/12/23',
  '0',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '49',
  '課長クラス'],
 ['33047',
  '2018/12/29',
  'レイノス',
  '2018/12/29',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '45',
  '部長クラス'],
 ['33125',
  '2019/01/01',
  'ロンザン',
  '2019/01/01',
  '0',
  '',
  'Indeed / cpc',
  'indeed4-2',
  '(not set)',
  '(not set)',
  '',
  '56',
  '部長クラス'],
 ['33207',
  '2019/01/03',
  'ロンザン',
  '2019/01/03',
  '対面',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '56',
  '部長クラス'],
 ['33429',
  '2019/01/06',
  'レイノス',
  '2019/01/06',
  '0',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '34',
  '主任・主査クラス'],
 ['33566',
  '2019/01/09',
  'レイノス',
  'コールセンター',
  'TV会議',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '53',
  '部長クラス'],
 ['33611',
  '2019/01/10',
  'ロンザン',
  '2019/10/28',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '47',
  '社長・会長クラス'],
 ['33792',
  '2019/01/15',
  'ロンザン',
  '2019/01/15',
  '対面',
  '',
  'fb_ad_top / display',
  'fb-adset4',
  '(not set)',
  '(not set)',
  '',
  '57',
  '部長クラス'],
 ['34115',
  '2019/01/21',
  'レイノス',
  '2019/01/21',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '55',
  '部長クラス'],
 ['34298',
  '2019/01/23',
  'レイノス',
  'コールセンター',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '45',
  '課長クラス'],
 ['34308',
  '2019/01/23',
  'ロンザン',
  '2019/08/09',
  'TV会議',
  '',
  'yahoo / organic',
  '(not set)',
  '(not set)',
  '(not provided)',
  '',
  '54',
  '部長クラス'],
 ['34481',
  '2019/01/26',
  'レイノス',
  '2019/01/26',
  '対面',
  '',
  'google / cpc',
  '【全国】指名_年齢不明_SN（カテゴリーA）',
  '転職先は経営者で決める',
  '転機',
  '',
  '43',
  '部長クラス'],
 ['34487',
  '2019/01/26',
  'ロンザン',
  '2019/01/26',
  'TV会議',
  '',
  'google / cpc',
  '【全国】年収上位_SN（カテゴリーA）',
  '社長の右腕、経営幹部案件ご用意',
  '求人 経営者',
  '',
  '66',
  '部長クラス'],
 ['34612',
  '2019/01/28',
  'ロンザン',
  'コールセンター',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '52',
  '部長クラス'],
 ['34863',
  '2019/02/02',
  'ロンザン',
  '2019/02/02',
  '対面',
  '',
  'google / cpc',
  '【全国】指名_年収上位_SN（カテゴリーA）',
  '【逆求人】特別オファーが届く',
  '転機',
  '',
  '56',
  '部長クラス'],
 ['35127',
  '2019/02/06',
  'レイノス',
  '2019/02/06',
  '対面',
  '',
  'google / cpc',
  '【全国】ミドル_SN（カテゴリーB）',
  '社長の右腕、経営幹部案件ご用意',
  '転職 ハイクラス',
  '',
  '47',
  '役員クラス'],
 ['35136',
  '2019/02/06',
  'レイノス',
  '2019/02/06',
  '対面',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '48',
  '部長クラス'],
 ['35189',
  '2019/02/07',
  'ロンザン',
  '2019/02/07',
  'TV会議',
  '',
  'yahoo / cpc',
  '1598314751',
  '(not set)',
  '転機',
  '',
  '58',
  '部長クラス'],
 ['35391',
  '2019/02/10',
  'ロンザン',
  'コールセンター',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '50',
  '社長・会長クラス'],
 ['35522',
  '2019/02/12',
  'ロンザン',
  '2019/02/12',
  'TV会議',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '56',
  '課長クラス'],
 ['35851',
  '2019/02/19',
  'レイノス',
  '2019/02/19',
  'ZOOM',
  '',
  'fb_ad_top / display',
  'fb-adset6',
  '(not set)',
  '(not set)',
  '',
  '42',
  '部長クラス'],
 ['35887',
  '2019/02/19',
  'レイノス',
  '2019/02/19',
  '対面',
  '',
  'google / cpc',
  '【全国】年齢不明_SN（カテゴリーA）',
  '社長の右腕、経営幹部案件ご用意',
  '転職 幹部',
  '',
  '32',
  '部長クラス'],
 ['35971',
  '2019/02/21',
  'ロンザン',
  '2019/02/21',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '57',
  '部長クラス'],
 ['36037',
  '2019/02/23',
  'ロンザン',
  '2019/11/27',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '51',
  '部長クラス'],
 ['36167',
  '2019/02/26',
  'レイノス',
  '2019/12/18',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '44',
  '主任・主査クラス'],
 ['36173',
  '2019/02/26',
  'レイノス',
  '2019/02/26',
  '対面',
  '',
  'google / cpc',
  '【全国】ミドル_SN（カテゴリーB）',
  'CxOとして事業を牽引する',
  '転職 キャリア',
  '',
  '50',
  '役員クラス'],
 ['36212',
  '2019/02/27',
  'レイノス',
  '2019/02/27',
  '対面',
  '',
  'google / cpc',
  '【全国】年齢不明_SN（カテゴリーA）',
  '社長の右腕、経営幹部案件ご用意',
  '転職 経営者',
  '',
  '50',
  '役員クラス'],
 ['36307',
  '2019/02/28',
  'ロンザン',
  '2019/02/28',
  'Skype',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '57',
  '役員クラス'],
 ['36428',
  '2019/03/03',
  'ロンザン',
  '2019/03/03',
  '対面',
  '',
  'google / cpc',
  '【全国】指名_年収上位_SN（カテゴリーA）',
  '転職先は経営者で決める',
  '転機',
  '',
  '55',
  '部長クラス'],
 ['36951',
  '2019/03/14',
  'ロンザン',
  '2019/03/14',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '55',
  '部長クラス'],
 ['37111',
  '2019/03/18',
  'レイノス',
  '2019/03/18',
  'ZOOM',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '47',
  '部長クラス'],
 ['37154',
  '2019/03/19',
  'レイノス',
  '2019/03/19',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '50',
  '役員クラス'],
 ['37413',
  '2019/03/24',
  'ロンザン',
  '2019/03/24',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '51',
  '課長クラス'],
 ['37468',
  '2019/03/25',
  'ロンザン',
  '2019/03/25',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '60',
  '役員クラス'],
 ['37468',
  '2019/03/25',
  'ロンザン',
  '2019/03/25',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '60',
  '役員クラス'],
 ['37826',
  '2019/04/02',
  'ロンザン',
  '2019/04/02',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '52',
  '部長クラス'],
 ['37991',
  '2019/04/05',
  'ロンザン',
  '2019/04/05',
  '対面',
  '',
  'google / cpc',
  '【東海】年収上位_SN（カテゴリーA）',
  '社長の右腕、経営幹部案件ご用意',
  '転職 キャリア',
  '',
  '52',
  '部長クラス'],
 ['37993',
  '2019/04/05',
  'ロンザン',
  '2019/04/05',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '55',
  '課長クラス'],
 ['38061',
  '2019/04/07',
  'ロンザン',
  '2019/04/07',
  'TV会議',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '49',
  '社長・会長クラス'],
 ['38242',
  '2019/04/10',
  'ロンザン',
  '2019/04/10',
  '対面',
  '',
  '(direct) / (none)',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '60',
  '役職なし'],
 ['38383',
  '2019/04/13',
  'レイノス',
  '2019/04/13',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '51',
  '役員クラス'],
 ['38446',
  '2019/04/14',
  'ロンザン',
  '2019/04/14',
  '電話',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '53',
  '部長クラス'],
 ['38538',
  '2019/04/15',
  'レイノス',
  '2019/04/15',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '47',
  '課長クラス'],
 ['39036',
  '2019/04/24',
  'ロンザン',
  '2019/04/24',
  'TV会議',
  '',
  'google / cpc',
  '【全国】シニア_SN（カテゴリーB）',
  '定年前にキャリアの見直しを',
  '定年退職 キャリア',
  '',
  '55',
  '役員クラス'],
 ['39235',
  '2019/04/29',
  'レイノス',
  '2019/04/29',
  '対面',
  '',
  'yahoo / cpc',
  '1593591720',
  '(not set)',
  '求人 キャリア',
  '',
  '45',
  '課長クラス'],
 ['39401',
  '2019/05/02',
  'ロンザン',
  '2019/05/02',
  '対面',
  '',
  'zeals_ad / chat_cpf',
  'shot',
  '(not set)',
  '(not set)',
  '(not set)',
  '52',
  '役員クラス'],
 ['39920',
  '2019/05/14',
  'ロンザン',
  '2019/05/14',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '54',
  '課長クラス'],
 ['40126',
  '2019/05/19',
  'ロンザン',
  '2019/10/29',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '49',
  '役員クラス'],
 ['40237',
  '2019/05/22',
  'ロンザン',
  '2019/05/22',
  '対面',
  '',
  'google / cpc',
  '【全国】年齢不明_SN（カテゴリーA）',
  '社長の右腕、経営幹部案件ご用意',
  '転職 マネージャー',
  '',
  '63',
  '顧問'],
 ['40238',
  '2019/05/22',
  'ロンザン',
  '2019/05/22',
  '対面',
  '',
  'google / cpc',
  '【全国】シニア_SN（カテゴリーB）',
  '定年前にキャリアの見直しを',
  '定年 キャリア',
  '',
  '59',
  '部長クラス'],
 ['40266',
  '2019/05/23',
  'ロンザン',
  '2019/05/23',
  'ZOOM',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '63',
  '部長クラス'],
 ['40322',
  '2019/05/24',
  'ロンザン',
  '2019/05/24',
  '対面',
  '',
  'Indeed / organic',
  'Indeed',
  '(not set)',
  '(not set)',
  '',
  '62',
  '顧問'],
 ['40425',
  '2019/05/27',
  'ロンザン',
  '2019/05/27',
  '対面',
  '',
  '(direct) / (none)',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '55',
  '課長クラス'],
 ['40506',
  '2019/05/28',
  'ロンザン',
  '2019/05/28',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '50',
  '社長・会長クラス'],
 ['40566',
  '2019/05/29',
  'レイノス',
  '2019/05/29',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '49',
  '部長クラス'],
 ['40640',
  '2019/05/30',
  'レイノス',
  '2019/05/30',
  '対面',
  '',
  'google / cpc',
  '【全国】年齢不明_SN（カテゴリーA）',
  'スカウトを受けて転職',
  'オファー キャリア',
  '',
  '42',
  '役員クラス'],
 ['40717',
  '2019/06/01',
  'ロンザン',
  '2019/06/01',
  '対面',
  '',
  'google / cpc',
  '【全国】シニア_SN（カテゴリーB）',
  '社長の右腕、経営幹部案件ご用意',
  '転職 60歳',
  '',
  '61',
  '部長クラス'],
 ['40949',
  '2019/06/05',
  'ロンザン',
  '2019/06/05',
  'TV会議',
  '',
  'google / cpc',
  '【近畿】ミドル_SN（カテゴリーB）',
  '社長の右腕、経営幹部案件ご用意',
  '求人 経営者',
  '',
  '58',
  '部長クラス'],
 ['41036',
  '2019/06/07',
  'ロンザン',
  '2019/06/07',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '54',
  '部長クラス'],
 ['41204',
  '2019/06/11',
  'レイノス',
  '2019/06/11',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '46',
  '課長クラス'],
 ['41240',
  '2019/06/12',
  'ロンザン',
  '2019/06/12',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '59',
  '課長クラス'],
 ['41279',
  '2019/06/12',
  'ロンザン',
  '2019/08/09',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '82',
  '部長クラス'],
 ['41328',
  '2019/06/13',
  'ロンザン',
  '2019/06/13',
  'ZOOM',
  '',
  'google / cpc',
  '【全国】シニア_SN（カテゴリーB）',
  '社長の右腕として採用',
  '求人 キャリア',
  '',
  '59',
  '部長クラス'],
 ['41337',
  '2019/06/13',
  'ロンザン',
  '2019/08/07',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset4',
  '(not set)',
  '(not set)',
  '',
  '51',
  '部長クラス'],
 ['41432',
  '2019/06/15',
  'ロンザン',
  '2019/06/15',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '54',
  '部長クラス'],
 ['41437',
  '2019/06/15',
  'ロンザン',
  '2019/06/15',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '55',
  '役員クラス'],
 ['41555',
  '2019/06/17',
  'ロンザン',
  '2019/06/17',
  '対面',
  '',
  'google / cpc',
  '【全国】シニア_SN（カテゴリーB）',
  '特別オファーが届く',
  'ヘッドハンティング キャリア',
  '',
  '57',
  '部長クラス'],
 ['41851',
  '2019/06/23',
  'ロンザン',
  '2022/11/14',
  'ZOOM',
  '',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  '',
  '52',
  '部長クラス'],
 ['41872',
  '2019/06/24',
  'ロンザン',
  '2019/06/24',
  '対面',
  '',
  'google / cpc',
  '【全国】指名_ミドル_SN（カテゴリーB）',
  '特別オファーが届く',
  '転機',
  '',
  '54',
  '課長クラス'],
 ['42146',
  '2019/06/30',
  'ロンザン',
  '2019/06/30',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '57',
  '部長クラス'],
 ['42184',
  '2019/06/30',
  'ロンザン',
  '2019/06/30',
  'ZOOM',
  '',
  'fb_ad / display',
  'fb-adset2',
  '(not set)',
  '(not set)',
  '',
  '50',
  '役職なし'],
 ['42272',
  '2019/07/02',
  'ロンザン',
  '2019/08/07',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '55',
  '部長クラス'],
 ['42460',
  '2019/07/06',
  'レイノス',
  '2019/07/06',
  '対面',
  '',
  'google / cpc',
  '【全国】ミドル_SN（カテゴリーB）',
  'CxOとして事業を牽引する',
  '中途採用 キャリア',
  '',
  '',
  ''],
 ['42556',
  '2019/07/08',
  'ロンザン',
  '2019/07/08',
  'TV会議',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '60',
  '部長クラス'],
 ['42754',
  '2019/07/12',
  'ロンザン',
  '2019/07/12',
  '対面',
  '',
  'shachomeikan.jp / referral',
  '(not set)',
  '(not set)',
  '(not set)',
  '',
  '',
  ''],
 ['42959',
  '2019/07/17',
  'ロンザン',
  '2019/07/17',
  'TV会議',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '51',
  '部長クラス'],
 ['42991',
  '2019/07/18',
  'ロンザン',
  '2019/07/18',
  'TV会議',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '54',
  '社長・会長クラス'],
 ['43037',
  '2019/07/19',
  'ロンザン',
  '2019/07/19',
  '対面',
  '',
  'google / cpc',
  '【全国】SDC_シニア・その他統合_DN（カテゴリーB）',
  '(not set)',
  '(not set)',
  '',
  '55',
  '部長クラス'],
 ['43038',
  '2019/07/19',
  'ロンザン',
  '2019/12/26',
  '電話orTV会議',
  '',
  'yahoo / cpc',
  '1598314733',
  '(not set)',
  '転機',
  '',
  '58',
  '主任・主査クラス'],
 ['43088',
  '2019/07/20',
  'ロンザン',
  '2019/07/20',
  'ZOOM',
  '',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  '',
  '51',
  '役員クラス'],
 ['43122',
  '2019/07/21',
  'レイノス',
  '2019/07/21',
  '対面',
  '',
  'google / cpc',
  '【近畿】指名_年収上位_SN（カテゴリーA）',
  '逆求人型転職は『転機』',
  '転機',
  '',
  '44',
  'リーダークラス'],
 ['43159',
  '2019/07/22',
  'ロンザン',
  '2019/07/22',
  '対面',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '53',
  'リーダークラス'],
 ['43358',
  '2019/07/28',
  'ロンザン',
  '2019/07/28',
  '電話',
  '',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  '',
  '54',

In [222]:
#ZEALSシートにコピペ
SPREADSHEET_ID = '1EglGY_Lf1kvHqZTpow4F2ksD20xD9J8G1oaMIjtyj78'
service = ps.get_auth(SCOPES, json_path)
Sheet_NAME = 'user!A'
Sheet_row = '2'
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,adinfoA,service)

## 広告費

In [223]:
#LINE広告費を取得する
SPREADSHEET_ID = '14vXxjcdlyY463QjrtEnCw7pJ0oLStXZD8Q42IdW2Zd4'
Sheet_NAME = '広告費!A'
Sheet_row = ":T"
RANGE_NAME = Sheet_NAME+Sheet_row
adcost = ps.get_ss(SPREADSHEET_ID,RANGE_NAME,service)

In [224]:
adcost_nm = adcost.copy()

In [225]:
adcost_line = adcost[["date","LINE CPC","LINE リタゲ","LINE CPF"]]
adcost_line

            date LINE CPC LINE リタゲ LINE CPF
1     2019/01/01                 0
2     2019/01/02                 0
3     2019/01/03                 0
4     2019/01/04                 0
5     2019/01/05                 0
...          ...      ...      ...      ...
4210  2030/07/11                 0
4211  2030/07/12                 0
4212  2030/07/13                 0
4213  2030/07/14                 0
4214  2030/07/15                 0

[4214 rows x 4 columns]

In [226]:
adcost_nm.replace([np.inf, -np.inf], np.nan, inplace=True)
adcost_nm.fillna('', inplace=True)
adcost_nm = adcost_nm.values.tolist()

adcost_line.replace([np.inf, -np.inf], np.nan, inplace=True)
adcost_line.fillna('', inplace=True)
adcost_line = adcost.values.tolist()

C:\Users\suehara\AppData\Local\Temp\ipykernel_32552\3808569263.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adcost_line.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\suehara\AppData\Local\Temp\ipykernel_32552\3808569263.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adcost_line.fillna('', inplace=True)

In [227]:
#LINEシートへコピペ
SPREADSHEET_ID = '1EglGY_Lf1kvHqZTpow4F2ksD20xD9J8G1oaMIjtyj78'
service = ps.get_auth(SCOPES, json_path)
Sheet_NAME = '広告費!A'
Sheet_row = '2'
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,adcost_nm,service)

In [228]:
#NMシートコピペ
SPREADSHEET_ID = '1d1uYQMCIhJGMlUe4S8m56Bd_ZS4_V-FUEtPjUlgpn9Y'
service = ps.get_auth(SCOPES, json_path)
Sheet_NAME = 'adcost!A'
Sheet_row = '2'
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,adcost_nm,service)

In [229]:
#CAシートコピペ
SPREADSHEET_ID = '1fVbpOYwIRsbW69EDsbJlTJwJVPTexi8RoMd3ahiO-IA'
service = ps.get_auth(SCOPES, json_path)
Sheet_NAME = '広告費!A'
Sheet_row = '2'
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,adcost_nm,service)

## 初期交渉情報取得

In [230]:
adinfoB = adinfo.copy()

In [231]:
adinfoB

,tenki_id,登録日時,フリ先,手上げ日付,本手上げ,KN共有日,参照元/メディア,キャンペーン,広告ID,KWD,,年齢,役職
1,1070,2016/09/17,ロンザン,2020/05/20,ZOOM,,,,,,,49,部長クラス
2,2748,2017/02/06,ロンザン,2017/02/06,,,,,,,,59,役員クラス
3,7024,2017/08/07,ロンザン,2017/08/07,,,google_SHIMEI / cpc,(not set),(not set),(not set),,55,リーダークラス
4,8539,2017/09/15,レイノス,2017/09/15,,,fb_ad / display,(not set),(not set),(not set),,35,リーダークラス
5,9502,2017/10/05,レイノス,2017/10/05,0,,yahoo_Ten / cpc_CA,(not set),(not set),(not set),,45,役員クラス
...,...,...,...,...,...,...,...,...,...,...,...,...,...
85875,140722,2026/07/20,ロンザン,2026/07/21,TRUE,2026/07/21,facebookcasm / display,CP02,ADS11,(not set),F00265,51,部長クラス
85876,140723,2026/07/21,ロンザン,2026/07/21,TRUE,2026/07/21,(not set),(not set),,(not set),,58,部長クラス
85877,140724,2026/07/21,,,,,(not set),(not set),,(not set),,57,部長クラス
85878,140725,2026/07/21,ロンザン,2026/07/21,TRUE,2026/07/21,(not set),(not set),,(not set),,59,部長クラス
85879,140726,2026/07/21,ロンザン,2026/07/21,TRUE,2026/07/21,(not set),(not set),,(not set),,46,課長クラス

In [232]:
rzshokikosho_query = """
WITH
-- ステップ1: 必要なテーブルをJOINし、各レコードの基本情報を計算
base_data AS (
  SELECT
    s.kohosha_id,
    k.tenki_id,
    s.kosho_setteibi,
    s.kosho_yoteibi,
    s.kosho_jisshibi,
    s.kosho_seq,
    s.cxl_riyu,
    -- APsource: 複数の名称を'その他'にまとめるなど、カテゴリを整形
    CASE
      WHEN consts1.name IN ('HP反響', '上場企業役員DM', 'Gアポ') THEN 'その他'
      WHEN consts1.name = '社外取締役名鑑　候補者' THEN '顧問名鑑登録　解放者'
      ELSE consts1.name
    END AS APsource,
    syi2.sei_plus AS ap_kakutokusha,
    -- 面談担当者: syainテーブルに存在すればsei_plusを、なければ元のIDを使用
    COALESCE(syi1.sei_plus, s.mendan_tanto) AS mendan_tanto,
    -- 実施ステータス: フラグ値などを元に分かりやすい文字列に変換
    CASE
      WHEN s.kosho_yoteibi >= CURRENT_DATE('Asia/Tokyo') THEN '実施前'
      WHEN s.jisshi_flag = 2 AND s.deleted = 2 THEN 'CXL'
      WHEN s.jisshi_flag = 0 AND s.deleted = 0 AND s.nittei_chosei = 1 THEN '日程調整中'
      WHEN s.jisshi_flag = 1 THEN '実施'
      WHEN s.jisshi_flag = 0 THEN '未報告'
      ELSE CAST(s.jisshi_flag AS STRING)
    END AS jisshi,
    -- 移籍意欲: 新しい値があれば優先し、なければ古い値を使用
    COALESCE(consts2.name, consts3.name) AS iseki_iyoku,
    -- 前回実施日からの経過日数: LAG関数で候補者ごとに前回交渉の実施日を取得して計算
    DATE_DIFF(s.kosho_setteibi, LAG(s.kosho_jisshibi) OVER (PARTITION BY s.kohosha_id ORDER BY s.kosho_jisshibi), DAY) AS keikabi
  FROM
    `r-group-bigdata..live_rhs.shokikoshos` AS s
    LEFT JOIN `r-group-bigdata.live_rhs.kohoshas` AS k ON s.kohosha_id = k.id
    LEFT JOIN `r-group-bigdata.live_company.syain` AS syi1 ON s.mendan_tanto = syi1.user_id
    LEFT JOIN `r-group-bigdata.live_company.syain` AS syi2 ON s.ap_kakutoku = syi2.user_id
    -- sys_constsテーブルへのJOINを最適化。必要なgroup_codeごとにJOINを分ける
    LEFT JOIN `r-group-bigdata.live_rhs.sys_consts` AS consts1 ON s.ap_source = consts1.code AND consts1.group_code = 19
    LEFT JOIN `r-group-bigdata.live_rhs.sys_consts` AS consts2 ON k.iseki_iyoku_new = consts2.code AND consts2.group_code = 5100
    LEFT JOIN `r-group-bigdata.live_rhs.sys_consts` AS consts3 ON s.iseki_iyoku = consts3.code AND consts3.group_code = 5100
),

-- ステップ2: ステップ1で計算したAPsourceを元に、前回からの変更を検知
final_data AS (
  SELECT
    *,
    -- APsourceが前回から変更されたかのフラグを計算
    CASE
      -- LAG関数で取得した1つ前のAPsourceと比較
      WHEN APsource != LAG(APsource) OVER (PARTITION BY kohosha_id ORDER BY kosho_setteibi) THEN 1
      ELSE 0
    END AS APS_change
  FROM
    base_data
)

-- 最終的なアウトプット: 必要なカラムを選択し、最終的なフラグを計算
SELECT
  kohosha_id,
  tenki_id,
  APsource,
  ap_kakutokusha,
  mendan_tanto,
  kosho_setteibi,
  kosho_yoteibi,
  kosho_jisshibi,
  jisshi,
  kosho_seq,
  APS_change,
  -- 再フラグ: 複数の条件に基づいてフラグを立てる
  CASE
    WHEN kosho_seq = 1 THEN 1       -- 最初の交渉
    WHEN APS_change = 1 THEN 1     -- APsourceが変更された場合
    WHEN keikabi > 90 THEN 2       -- 前回の交渉から90日以上経過した場合
    ELSE 0
  END AS sai_flg,
  cxl_riyu,
  iseki_iyoku
FROM
  final_data
WHERE
  -- 元のクエリと同じフィルタ条件
  APsource = '転機社長名鑑'
  AND kosho_setteibi >= DATE '2019-09-30'
ORDER BY
  kosho_setteibi ASC;
"""

client = bigquery.Client(credentials=credentials, project=credentials.project_id)
rzshokikosho = client.query(rzshokikosho_query).result().to_dataframe()

In [233]:
adinfoB = adinfoB.rename(columns={"ID":"tenki_id"})
rzshokikosho["tenki_id"] = rzshokikosho["tenki_id"].astype(str)
shokikosho = pd.merge(rzshokikosho,adinfoB,on=("tenki_id"),how=("left"))

In [234]:
rzshokikosho

,kohosha_id,tenki_id,APsource,ap_kakutokusha,mendan_tanto,kosho_setteibi,kosho_yoteibi,kosho_jisshibi,jisshi,kosho_seq,APS_change,sai_flg,cxl_riyu,iseki_iyoku
0,14985,44305,転機社長名鑑,内藤ち,勝股大,2019-09-30,2019-10-01,2019-10-01,実施,1,0,1,None,None
1,15003,46161,転機社長名鑑,内藤ち,三木茉,2019-09-30,2019-10-11,2019-10-11,実施,1,0,1,None,None
2,15002,46151,転機社長名鑑,内藤ち,山田真２,2019-09-30,2019-10-11,2019-10-11,実施,1,0,1,None,None
3,15001,46191,転機社長名鑑,内藤ち,松島せ,2019-09-30,2019-10-02,2019-10-02,実施,1,0,1,None,None
4,15000,46144,転機社長名鑑,内藤ち,運上禎,2019-09-30,2019-10-02,2019-10-02,実施,1,0,1,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38993,77333,140692,転機社長名鑑,内藤ち,前川天,2026-07-22,2026-07-28,NaT,実施前,1,0,1,None,None
38994,77334,140439,転機社長名鑑,内藤ち,森俊,2026-07-22,2026-07-27,NaT,実施前,1,0,1,None,None
38995,77335,140719,転機社長名鑑,内藤ち,松澤神,2026-07-22,2026-07-28,NaT,実施前,1,0,1,None,None
38996,77336,140733,転機社長名鑑,内藤ち,aya-takeshita,2026-07-22,2026-07-27,NaT,実施前,1,0,1,None,None
38997,37531,97888,転機社長名鑑,前川天,前川天,2026-07-23,2026-07-24,NaT,実施前,2,0,0,None,C：良い話があれば検討したい

In [235]:
rzshokikosho = shokikosho[['tenki_id','登録日時','kosho_setteibi','kosho_jisshibi', '参照元/メディア','キャンペーン', '広告ID', 'KWD','sai_flg']]
shokikosho = rzshokikosho.sort_values(by='kosho_setteibi')

In [236]:
shokikosho.columns

Index(['tenki_id', '登録日時', 'kosho_setteibi', 'kosho_jisshibi', '参照元/メディア',
       'キャンペーン', '広告ID', 'KWD', 'sai_flg'],
      dtype='object')

In [237]:
shokikosho

,tenki_id,登録日時,kosho_setteibi,kosho_jisshibi,参照元/メディア,キャンペーン,広告ID,KWD,sai_flg
0,44305,NaN,2019-09-30,2019-10-01,NaN,NaN,NaN,NaN,1
18,44489,NaN,2019-09-30,2019-10-01,NaN,NaN,NaN,NaN,1
17,45259,NaN,2019-09-30,2019-10-02,NaN,NaN,NaN,NaN,1
16,45920,NaN,2019-09-30,2019-10-02,NaN,NaN,NaN,NaN,1
15,45344,NaN,2019-09-30,2019-10-02,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...
38979,<NA>,NaN,2026-07-22,NaT,NaN,NaN,NaN,NaN,1
38978,<NA>,NaN,2026-07-22,NaT,NaN,NaN,NaN,NaN,1
38996,140733,NaN,2026-07-22,NaT,NaN,NaN,NaN,NaN,1
38986,140703,2026/07/19,2026-07-22,NaT,yahoo / display,y01_rtg,444,(not set),1
38997,97888,2022/07/17,2026-07-23,NaT,zeals_ad / chat_cpf,shot,(not set),(not set),0

In [238]:
shokikosho["tenki_id"] = shokikosho["tenki_id"].str.replace('<NA>', '')
shokikosho["登録日時"] = shokikosho["登録日時"].str.replace('NaN', '')
shokikosho["kosho_setteibi"] = shokikosho["kosho_setteibi"].astype(str).str.replace('None', '')
shokikosho["kosho_jisshibi"] = shokikosho["kosho_jisshibi"].astype(str).str.replace('None', '')
shokikosho["参照元/メディア"] = shokikosho["参照元/メディア"].str.replace('NaN', '')
shokikosho["キャンペーン"] = shokikosho["キャンペーン"].str.replace('NaN', '')
shokikosho["広告ID"] = shokikosho["広告ID"].str.replace('NaN', '')
shokikosho["KWD"] = shokikosho["KWD"].str.replace('NaN', '')

In [239]:
shokikosho.replace([np.inf, -np.inf], np.nan, inplace=True)
shokikosho.fillna('', inplace=True)
shokikosho = shokikosho.values.tolist()

In [240]:
shokikosho

[['44305', '', '2019-09-30', '2019-10-01', '', '', '', '', 1],
 ['44489', '', '2019-09-30', '2019-10-01', '', '', '', '', 1],
 ['45259', '', '2019-09-30', '2019-10-02', '', '', '', '', 1],
 ['45920', '', '2019-09-30', '2019-10-02', '', '', '', '', 1],
 ['45344', '', '2019-09-30', '2019-10-02', '', '', '', '', 1],
 ['45929', '', '2019-09-30', '2019-10-02', '', '', '', '', 1],
 ['45978', '', '2019-09-30', '2019-10-09', '', '', '', '', 1],
 ['46052', '', '2019-09-30', '2019-10-09', '', '', '', '', 1],
 ['45966', '', '2019-09-30', '2019-10-21', '', '', '', '', 1],
 ['45019', '', '2019-09-30', '2019-10-07', '', '', '', '', 1],
 ['45369', '', '2019-09-30', '2019-10-10', '', '', '', '', 2],
 ['46110', '', '2019-09-30', '2019-10-07', '', '', '', '', 1],
 ['46151', '', '2019-09-30', '2019-10-11', '', '', '', '', 1],
 ['46191', '', '2019-09-30', '2019-10-02', '', '', '', '', 1],
 ['46144',
  '2019/09/28',
  '2019-09-30',
  '2019-10-02',
  'google / cpc',
  '【近畿】シニア_検索総合_SN（カテゴリーB）',
  '(not set)',
  '求人 キャリア',
  1],
 ['46161', '', '2019-09-30', '2019-10-11', '', '', '', '', 1],
 ['46120', '', '2019-09-30', '2019-10-02', '', '', '', '', 1],
 ['46136', '', '2019-09-30', '2019-10-02', '', '', '', '', 1],
 ['46081', '', '2019-09-30', 'NaT', '', '', '', '', 1],
 ['44849', '', '2019-10-01', '2019-10-21', '', '', '', '', 1],
 ['46163', '', '2019-10-01', '2019-10-07', '', '', '', '', 1],
 ['', '', '2019-10-01', '2019-10-10', '', '', '', '', 1],
 ['46213', '', '2019-10-01', '2019-10-07', '', '', '', '', 1],
 ['', '', '2019-10-01', '2019-10-11', '', '', '', '', 1],
 ['', '', '2019-10-01', '2019-10-07', '', '', '', '', 1],
 ['', '', '2019-10-01', 'NaT', '', '', '', '', 1],
 ['46285',
  '2019/10/01',
  '2019-10-01',
  '2019-10-08',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  1],
 ['46076', '', '2019-10-01', '2019-10-07', '', '', '', '', 1],
 ['', '', '2019-10-01', 'NaT', '', '', '', '', 1],
 ['46091', '', '2019-10-01', '2019-10-31', '', '', '', '', 1],
 ['', '', '2019-10-01', '2019-10-09', '', '', '', '', 1],
 ['46246', '', '2019-10-01', '2019-10-07', '', '', '', '', 1],
 ['46286',
  '2019/10/01',
  '2019-10-01',
  '2019-10-07',
  'yahoo / display',
  '(not set)',
  '(not set)',
  '(not set)',
  1],
 ['', '', '2019-10-01', '2019-10-16', '', '', '', '', 2],
 ['107973',
  '2023/08/14',
  '2019-10-01',
  '2019-10-08',
  'zeals_ad / chat_cpf',
  'shot',
  '(not set)',
  '(not set)',
  1],
 ['46209', '', '2019-10-01', '2019-10-07', '', '', '', '', 1],
 ['46092', '', '2019-10-01', '2019-10-11', '', '', '', '', 1],
 ['', '', '2019-10-01', '2019-10-10', '', '', '', '', 1],
 ['', '', '2019-10-02', '2019-10-15', '', '', '', '', 1],
 ['46149', '', '2019-10-02', '2019-10-24', '', '', '', '', 1],
 ['46156', '', '2019-10-02', '2019-10-15', '', '', '', '', 1],
 ['46119', '', '2019-10-02', '2019-10-09', '', '', '', '', 1],
 ['', '', '2019-10-02', '2019-10-08', '', '', '', '', 1],
 ['46259', '', '2019-10-02', 'NaT', '', '', '', '', 1],
 ['46260', '', '2019-10-02', '2019-10-09', '', '', '', '', 1],
 ['45795', '', '2019-10-02', '2019-10-15', '', '', '', '', 1],
 ['45466', '', '2019-10-02', '2019-10-09', '', '', '', '', 1],
 ['44842',
  '2019/09/01',
  '2019-10-02',
  '2019-10-07',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  1],
 ['42816', '', '2019-10-02', '2019-10-15', '', '', '', '', 1],
 ['46281',
  '2019/10/01',
  '2019-10-02',
  '2019-10-15',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['', '', '2019-10-02', '2019-10-08', '', '', '', '', 1],
 ['46323',
  '2019/10/01',
  '2019-10-02',
  '2019-10-11',
  'smartnews_ad / display',
  'all_LALtarget_smartnews',
  '(not set)',
  '(not set)',
  1],
 ['45673', '', '2019-10-02', '2019-10-11', '', '', '', '', 1],
 ['46212',
  '2019/09/29',
  '2019-10-02',
  '2019-10-07',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['46153', '', '2019-10-02', '2019-10-08', '', '', '', '', 1],
 ['', '', '2019-10-02', '2019-10-11', '', '', '', '', 1],
 ['46175', '', '2019-10-02', 'NaT', '', '', '', '', 1],
 ['', '', '2019-10-02', '2019-10-08', '', '', '', '', 1],
 ['44967', '', '2019-10-02', '2019-10-11', '', '', '', '', 1],
 ['', '', '2019-10-02', '2019-10-08', '', '', '', '', 1],
 ['46134', '', '2019-10-02', '2019-10-07', '', '', '', '', 1],
 ['', '', '2019-10-02', '2019-10-11', '', '', '', '', 1],
 ['', '', '2019-10-07', '2019-10-07', '', '', '', '', 2],
 ['', '', '2019-10-07', '2019-10-07', '', '', '', '', 2],
 ['', '', '2019-10-07', '2019-10-07', '', '', '', '', 2],
 ['', '', '2019-10-07', '2019-10-09', '', '', '', '', 1],
 ['', '', '2019-10-07', '2019-10-07', '', '', '', '', 0],
 ['', '', '2019-10-07', '2019-10-07', '', '', '', '', 0],
 ['', '', '2019-10-07', '2019-10-09', '', '', '', '', 1],
 ['', '', '2019-10-07', 'NaT', '', '', '', '', 1],
 ['45745', '', '2019-10-07', '2019-10-18', '', '', '', '', 1],
 ['', '', '2019-10-07', '2019-10-10', '', '', '', '', 1],
 ['', '', '2019-10-07', '2019-10-09', '', '', '', '', 1],
 ['', '', '2019-10-07', '2019-10-07', '', '', '', '', 2],
 ['', '', '2019-10-07', '2019-10-15', '', '', '', '', 1],
 ['', '', '2019-10-07', '2019-10-15', '', '', '', '', 1],
 ['', '', '2019-10-07', '2019-10-21', '', '', '', '', 1],
 ['', '', '2019-10-07', 'NaT', '', '', '', '', 1],
 ['', '', '2019-10-07', '2019-10-10', '', '', '', '', 1],
 ['46201', '', '2019-10-07', '2019-10-11', '', '', '', '', 1],
 ['', '', '2019-10-08', '2019-12-12', '', '', '', '', 1],
 ['', '', '2019-10-08', '2019-10-15', '', '', '', '', 1],
 ['46425',
  '2019/10/04',
  '2019-10-08',
  '2019-10-10',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['44700',
  '2019/08/29',
  '2019-10-08',
  '2019-10-11',
  'fb_ad / display',
  'fb-adset4',
  '(not set)',
  '(not set)',
  1],
 ['', '', '2019-10-08', '2019-10-10', '', '', '', '', 1],
 ['', '', '2019-10-08', '2019-10-10', '', '', '', '', 1],
 ['', '', '2019-10-08', '2019-10-10', '', '', '', '', 1],
 ['', '', '2019-10-08', '2019-10-10', '', '', '', '', 1],
 ['', '', '2019-10-08', 'NaT', '', '', '', '', 1],
 ['', '', '2019-10-08', '2019-10-21', '', '', '', '', 1],
 ['', '', '2019-10-08', '2019-10-10', '', '', '', '', 1],
 ['46399',
  '2019/10/03',
  '2019-10-08',
  'NaT',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['', '', '2019-10-08', '2019-10-09', '', '', '', '', 1],
 ['', '', '2019-10-08', '2019-10-10', '', '', '', '', 1],
 ['46501',
  '2019/10/05',
  '2019-10-08',
  '2019-10-16',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  1],
 ['36669', '', '2019-10-08', 'NaT', '', '', '', '', 1],
 ['46426',
  '2019/10/04',
  '2019-10-08',
  '2019-10-16',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['', '', '2019-10-08', '2019-10-10', '', '', '', '', 1],
 ['45089', '', '2019-10-08', '2019-10-23', '', '', '', '', 1],
 ['46449',
  '2019/10/04',
  '2019-10-08',
  '2019-10-16',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  1],
 ['46359',
  '2019/10/02',
  '2019-10-08',
  '2019-10-15',
  'smartnews_ad / display',
  'all_LALtarget_smartnews',
  '(not set)',
  '(not set)',
  1],
 ['46385',
  '2019/10/03',
  '2019-10-08',
  '2019-10-16',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['46438',
  '2019/10/04',
  '2019-10-08',
  '2019-10-15',
  'google / cpc',
  '【全国】ミドル_検索総合_SN（カテゴリーB）',
  '(not set)',
  'スカウト エグゼクティブ',
  1],
 ['46450',
  '2019/10/04',
  '2019-10-08',
  '2019-10-11',
  'google / cpc',
  '【work】ディスプレイ',
  '(not set)',
  '(not set)',
  1],
 ['46462',
  '2019/10/05',
  '2019-10-08',
  '2019-10-11',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  2],
 ['46404',
  '2019/10/03',
  '2019-10-08',
  '2019-10-10',
  'google / cpc',
  '【work】ディスプレイ',
  '(not set)',
  '(not set)',
  1],
 ['', '', '2019-10-08', '2019-10-11', '', '', '', '', 1],
 ['46457',
  '2019/10/05',
  '2019-10-08',
  '2019-10-24',
  'google / cpc',
  '【全国】検索総合_SN（カテゴリーA）',
  '社長の右腕、経営幹部案件ご用意',
  '転職 エグゼクティブ',
  1],
 ['', '', '2019-10-09', '2019-10-11', '', '', '', '', 0],
 ['46412',
  '2019/10/03',
  '2019-10-09',
  '2019-10-15',
  'google / cpc',
  '【全国】ミドル_検索総合_SN（カテゴリーB）',
  '(not set)',
  '求人 ハイクラス',
  1],
 ['46402',
  '2019/10/03',
  '2019-10-09',
  '2019-10-16',
  'google / cpc',
  '【work】ディスプレイ',
  '(not set)',
  '(not set)',
  1],
 ['46405',
  '2019/10/03',
  '2019-10-09',
  '2019-10-18',
  'google / organic',
  '(not set)',
  '(not set)',
  '(not provided)',
  1],
 ['46492',
  '2019/10/05',
  '2019-10-09',
  '2019-10-25',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['46317',
  '2019/10/01',
  '2019-10-09',
  '2019-10-23',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  1],
 ['96543',
  '2022/06/17',
  '2019-10-09',
  '2019-10-15',
  'fb_ad / display',
  'nm_facebook',
  '02_20220531_FB_S_506',
  'normal',
  1],
 ['37641', '', '2019-10-09', '2019-10-15', '', '', '', '', 1],
 ['46296',
  '2019/10/01',
  '2019-10-09',
  '2019-10-16',
  'fb_ad / display',
  'fb-adset6',
  '(not set)',
  '(not set)',
  1],
 ['46598',
  '2019/10/07',
  '2019-10-09',
  '2019-10-15',
  'google / cpc',
  '【全国】検索総合_SN（カテゴリーA）',
  '(not set)',
  '転機',
  1],
 ['46564',
  '2019/10/07',
  '2019-10-09',
  '2019-10-18',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  1],
 ['46391',
  '2019/10/03',
  '2019-10-09',
  '2019-10-11',
  'google / organic',
  '(not set)',
  '(not set)',
  '(not provided)',
  1],
 ['', '', '2019-10-09', '2019-10-09', '', '', '', '', 2],
 ['', '', '2019-10-09', '2019-10-09', '', '', '', '', 2],
 ['46341',
  '2019/10/02',
  '2019-10-09',
  '2019-10-11',
  'fb_ad / display',
  'fb-adset6',
  '(not set)',
  '(not set)',
  1],
 ['46617',
  '2019/10/08',
  '2019-10-09',
  '2019-10-16',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  1],
 ['46597',
  '2019/10/07',
  '2019-10-09',
  '2019-10-18',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  1],
 ['46584',
  '2019/10/07',
  '2019-10-09',
  '2019-10-11',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  1],
 ['', '', '2019-10-09', '2019-10-09', '', '', '', '', 2],
 ['', '', '2019-10-10', '2019-10-15', '', '', '', '', 2],
 ['46469',
  '2019/10/05',
  '2019-10-10',
  '2019-10-16',
  '(direct) / (none)',
  '(not set)',
  '(not set)',
  '(not set)',
  1],
 ['39396', '', '2019-10-10', '2019-10-18', '', '', '', '', 1],
 ['46482',
  '2019/10/05',
  '2019-10-10',
  '2019-10-23',
  '(direct) / (none)',
  '(not set)',
  '(not set)',
  '(not set)',
  1],
 ['46507',
  '2019/10/06',
  '2019-10-10',
  '2019-10-21',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['46562',
  '2019/10/07',
  '2019-10-10',
  '2019-10-17',
  'google / cpc',
  '【全国】検索総合_SN（カテゴリーA）',
  '転職先は経営者で決める',
  '転機',
  1],
 ['46655',
  '2019/10/09',
  '2019-10-10',
  '2019-11-06',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['', '', '2019-10-10', '2019-10-15', '', '', '', '', 1],
 ['46109', '', '2019-10-10', '2019-11-01', '', '', '', '', 1],
 ['46629',
  '2019/10/08',
  '2019-10-10',
  '2019-10-25',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['', '', '2019-10-10', '2019-10-10', '', '', '', '', 2],
 ['46593',
  '2019/10/07',
  '2019-10-10',
  '2019-10-21',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  1],
 ['46362',
  '2019/10/02',
  '2019-10-10',
  '2019-10-18',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  1],
 ['44020', '', '2019-10-10', '2019-10-15', '', '', '', '', 1],
 ['46669',
  '2019/10/09',
  '2019-10-10',
  '2019-10-16',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  1],
 ['46658',
  '2019/10/09',
  '2019-10-10',
  '2019-10-21',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  1],
 ['', '', '2019-10-10', '2019-10-11', '', '', '', '', 1],
 ['46508',
  '2019/10/06',
  '2019-10-10',
  '2019-10-15',
  'google / cpc',
  '【全国】ミドル_検索総合_SN（カテゴリーB）',
  '(not set)',
  '転職 キャリア',
  1],
 ['44800', '', '2019-10-10', 'NaT', '', '', '', '', 1],
 ['34850', '', '2019-10-11', '2019-10-15', '', '', '', '', 1],
 ['46471',
  '2019/10/05',
  '2019-10-11',
  '2019-10-16',
  'google / cpc',
  '【全国】シニア_検索総合_SN（カテゴリーB）',
  '(not set)',
  '求人 エグゼクティブ',
  1],
 ['', '', '2019-10-11', '2019-10-11', '', '', '', '', 2],
 ['', '', '2019-10-11', '2019-10-17', '', '', '', '', 2],
 ['', '', '2019-10-11', '2019-10-13', '', '', '', '', 2],
 ['46537',
  '2019/10/06',
  '2019-10-11',
  '2019-10-16',
  'google / cpc',
  '【全国】シニア_検索総合_SN（カテゴリーB）',
  '(not set)',
  '転職 50代',
  2],
 ['46663',
  '2019/10/09',
  '2019-10-11',
  '2019-10-16',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['46344',
  '2019/10/02',
  '2019-10-11',
  '2019-10-16',
  'google / cpc',
  '【東海】シニア_検索総合_SN（カテゴリーB）',
  '(not set)',
  '転職 シニア',
  1],
 ['46614',
  '2019/10/08',
  '2019-10-11',
  '2019-10-25',
  'fb_ad / display',
  'fb-adset6',
  '(not set)',
  '(not set)',
  1],
 ['46621',
  '2019/10/08',
  '2019-10-11',
  '2019-10-15',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  1],
 ['46588',
  '2019/10/07',
  '2019-10-11',
  '2019-10-17',
  'google / cpc',
  '【全国】検索総合_SN（カテゴリーA）',
  '社長の右腕、経営幹部案件ご用意',
  '求人 ハイクラス',
  1],
 ['44700',
  '2019/08/29',
  '2019-10-11',
  '2019-10-11',
  'fb_ad / display',
  'fb-adset4',
  '(not set)',
  '(not set)',
  0],
 ['105210',
  '2023/05/28',
  '2019-10-11',
  '2019-10-18',
  'zeals_ad / chat_cpf',
  'shot',
  '(not set)',
  '(not set)',
  1],
 ['45822', '', '2019-10-11', '2019-10-16', '', '', '', '', 1],
 ['', '', '2019-10-11', '2019-10-15', '', '', '', '', 2],
 ['46651',
  '2019/10/09',
  '2019-10-11',
  '2019-10-21',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  1],
 ['', '', '2019-10-11', '2019-10-11', '', '', '', '', 2],
 ['46654',
  '2019/10/09',
  '2019-10-11',
  '2019-10-18',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  1],
 ['46671',
  '2019/10/09',
  '2019-10-11',
  '2019-10-23',
  'yahoo / cpc',
  '1593591594',
  '(not set)',
  '定年退職 キャリア',
  1],
 ['46633',
  '2019/10/08',
  '2019-10-11',
  '2019-10-18',
  '(direct) / (none)',
  '(not set)',
  '(not set)',
  '(not set)',
  1],
 ['46680',
  '2019/10/09',
  '2019-10-11',
  'NaT',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['46503',
  '2019/10/05',
  '2019-10-15',
  '2019-10-16',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  1],
 ['46667',
  '2019/10/09',
  '2019-10-15',
  '2019-10-23',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  1],
 ['46688',
  '2019/10/10',
  '2019-10-15',
  '2019-10-17',
  'Affiliate_AT / display',
  '(not set)',
  '(not set)',
  '(not set)',
  1],
 ['46419',
  '2019/10/03',
  '2019-10-15',
  '2019-10-24',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['37626', '', '2019-10-15', '2019-10-18', '', '', '', '', 1],
 ['46719',
  '2019/10/11',
  '2019-10-15',
  '2019-10-21',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['46686',
  '2019/10/10',
  '2019-10-15',
  '2019-10-18',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  1],
 ['', '', '2019-10-15', '2019-10-15', '', '', '', '', 2],
 ['', '', '2019-10-15', '2019-10-15', '', '', '', '', 2],
 ['', '', '2019-10-15', '2019-10-15', '', '', '', '', 2],
 ['46548',
  '2019/10/07',
  '2019-10-15',
  'NaT',
  'google / cpc',
  '【work】ディスプレイ',
  'C-300x600.jpg',
  '(not set)',
  1],
 ['46684',
  '2019/10/10',
  '2019-10-15',
  '2019-10-17',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  1],
 ['46801',
  '2019/10/13',
  '2019-10-16',
  '2019-10-24',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['46794',
  '2019/10/13',
  '2019-10-16',
  '2019-10-21',
  'yahoo / cpc',
  '1593395645',
  '(not set)',
  '求人 キャリア シニア',
  1],
 ['', '', '2019-10-16', '2019-10-21', '', '', '', '', 1],
 ['', '', '2019-10-16', '2019-10-23', '', '', '', '', 1],
 ['', '', '2019-10-16', '2019-10-28', '', '', '', '', 1],
 ['', '', '2019-10-16', '2019-10-21', '', '', '', '', 1],
 ['', '', '2019-10-16', '2019-10-25', '', '', '', '', 1],
 ['', '', '2019-10-16', '2019-10-28', '', '', '', '', 1],
 ['46489',
  '2019/10/05',
  '2019-10-16',
  '2019-10-21',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['', '', '2019-10-16', '2019-10-25', '', '', '', '', 1],
 ['41632', '', '2019-10-16', '2019-10-29', '', '', '', '', 1],
 ['46851',
  '2019/10/15',
  '2019-10-16',
  '2019-10-21',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['46514',
  '2019/10/06',
  '2019-10-16',
  '2019-12-02',
  'fb_ad / display',
  'fb-adset1',
  '(not set)',
  '(not set)',
  1],
 ['46082', '', '2019-10-16', '2019-11-01', '', '', '', '', 1],
 ['', '', '2019-10-16', '2019-10-16', '', '', '', '', 2],
 ['46755',
  '2019/10/12',
  '2019-10-16',
  '2019-10-21',
  'yahoo / cpc',
  '1598478186',
  '(not set)',
  '転機',
  1],
 ['', '', '2019-10-16', '2019-10-16', '', '', '', '', 2],
 ['', '', '2019-10-16', '2019-10-16', '', '', '', '', 2],
 ['46772',
  '2019/10/12',
  '2019-10-16',
  '2019-11-13',
  'fb_ad / display',
  'fb-adset6',
  '(not set)',
  '(not set)',
  1],
 ['', '', '2019-10-16', '2019-10-30', '', '', '', '', 2],
 ['46781',
  '2019/10/13',
  '2019-10-16',
  '2019-11-05',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  1],
 ['46726',
  '2019/10/11',
  '2019-10-16',
  '2019-10-18',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  1],
 ['46774',
  '2019/10/12',
  '2019-10-16',
  '2019-11-18',
  '#N/A',
  '#N/A',
  '#N/A',
  '#N/A',
  1],
 ['38568', '', '2019-10-17', '2019-11-06', '', '', '', '', 1],
 ['', '', '2019-10-17', '2019-10-25', '', '', '', '', 1],
 ['', '', '2019-10-17', '2019-10-21', '', '', '', '', 1],
 ['46822',
  '2019/10/14',
  '2019-10-17',
  '2019-10-23',
  'smartnews_ad / display',
  'all_LALtarget_smartnews',
  '(not set)',
  '(not set)',
  1],
 ['46730',
  '2019/10/11',
  '2019-10-17',
  '2019-10-24',
  'google / cpc',
  '【東海】検索総合_SN（カテゴリーA）',
  '社長の右腕、経営幹部案件ご用意',
  '求人 経営者',
  1],
 ['46838',
  '2019/10/14',
  '2019-10-17',
  '2019-11-11',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['46712',
  '2019/10/10',
  '2019-10-17',
  '2019-10-18',
  'google / cpc',
  '【東海】ディスプレイ統合_DN（カテゴリーA）',
  'A-728x90.jpg',
  '(not set)',
  1],
 ['40403', '', '2019-10-17', '2019-10-29', '', '', '', '', 1],
 ['46070', '', '2019-10-17', '2019-11-05', '', '', '', '', 1],
 ['46347',
  '2019/10/02',
  '2019-10-17',
  'NaT',
  'smartnews_ad / display',
  'all_rtg_smartnews',
  '(not set)',
  '(not set)',
  1],
 ['46737',
  '2019/10/11',
  '2019-10-17',
  '2019-11-11',
  'smartnews_ad / display',
  'all_LALtarget_smartnews',
  '(not set)',
  '(not set)',
  1],
 ['', '', '2019-10-17', '2019-10-23', '', '', '', '', 1],
 ['46819',
  '2019/10/14',
  '2019-10-17',
  '2019-10-23',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['', '', '2019-10-17', '2019-10-23', '', '', '', '', 1],
 ['46721',
  '2019/10/11',
  '2019-10-17',
  '2019-11-06',
  'Affiliate_A8 / display',
  '(not set)',
  '(not set)',
  '(not set)',
  1],
 ['', '', '2019-10-17', '2019-10-21', '', '', '', '', 1],
 ['', '', '2019-10-17', '2019-10-21', '', '', '', '', 1],
 ['46923',
  '2019/10/17',
  '2019-10-17',
  '2019-10-23',
  'google / organic',
  '(not set)',
  '(not set)',
  '(not provided)',
  1],
 ['', '', '2019-10-17', '2019-10-18', '', '', '', '', 1],
 ['', '', '2019-10-17', '2019-10-17', '', '', '', '', 2],
 ['', '', '2019-10-17', '2019-10-17', '', '', '', '', 2],
 ['82023',
  '2021/06/28',
  '2019-10-17',
  '2020-01-27',
  'google / organic',
  '(not set)',
  '(not set)',
  '(not provided)',
  2],
 ['', '', '2019-10-17', '2019-10-21', '', '', '', '', 2],
 ['46834',
  '2019/10/14',
  '2019-10-17',
  '2019-10-30',
  'google / cpc',
  '【近畿】シニア_検索総合_SN（カテゴリーB）',
  '(not set)',
  '定年 キャリア',
  1],
 ['46921',
  '2019/10/17',
  '2019-10-17',
  '2019-10-24',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['46898',
  '2019/10/16',
  '2019-10-17',
  '2019-10-23',
  'fb_ad / display',
  'fb-adset3',
  '(not set)',
  '(not set)',
  1],
 ['46892',

In [241]:
#シートにコピペ
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly',
          'https://www.googleapis.com/auth/spreadsheets']
json_path = r"Z:\Users\suehara\Documents\python\analysis\python_ss\credentials.json"
service = ps.get_auth(SCOPES,json_path)
SPREADSHEET_ID = '1Mvqe8nLhdiT9acCMA4cP-4MH5X4GmYPiC9OSqHTEHtk'
Sheet_NAME = 'rzdata!A'
Sheet_row = "3"
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,shokikosho,service)

In [242]:
# #NMのシートにコピペ
# service = ps.get_auth(SCOPES,json_path)
# SPREADSHEET_ID = '1d1uYQMCIhJGMlUe4S8m56Bd_ZS4_V-FUEtPjUlgpn9Y'
# Sheet_NAME = 'rzdata!A'
# Sheet_row = "3"
# RANGE_NAME = Sheet_NAME+Sheet_row
# ps.update_ss(SPREADSHEET_ID,RANGE_NAME,shokikosho,service)

In [243]:
#ZEALSのシートにコピペ
service = ps.get_auth(SCOPES,json_path)
SPREADSHEET_ID = '1EglGY_Lf1kvHqZTpow4F2ksD20xD9J8G1oaMIjtyj78'
Sheet_NAME = 'rzdata!A'
Sheet_row = "3"
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,shokikosho,service)

In [244]:
#CAのシートにコピペ
SPREADSHEET_ID = '1fVbpOYwIRsbW69EDsbJlTJwJVPTexi8RoMd3ahiO-IA'
Sheet_NAME = 'data!A'
Sheet_row = "3"
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,shokikosho,service)

## 本交渉情報取得

In [245]:
adinfoB

,tenki_id,登録日時,フリ先,手上げ日付,本手上げ,KN共有日,参照元/メディア,キャンペーン,広告ID,KWD,,年齢,役職
1,1070,2016/09/17,ロンザン,2020/05/20,ZOOM,,,,,,,49,部長クラス
2,2748,2017/02/06,ロンザン,2017/02/06,,,,,,,,59,役員クラス
3,7024,2017/08/07,ロンザン,2017/08/07,,,google_SHIMEI / cpc,(not set),(not set),(not set),,55,リーダークラス
4,8539,2017/09/15,レイノス,2017/09/15,,,fb_ad / display,(not set),(not set),(not set),,35,リーダークラス
5,9502,2017/10/05,レイノス,2017/10/05,0,,yahoo_Ten / cpc_CA,(not set),(not set),(not set),,45,役員クラス
...,...,...,...,...,...,...,...,...,...,...,...,...,...
85875,140722,2026/07/20,ロンザン,2026/07/21,TRUE,2026/07/21,facebookcasm / display,CP02,ADS11,(not set),F00265,51,部長クラス
85876,140723,2026/07/21,ロンザン,2026/07/21,TRUE,2026/07/21,(not set),(not set),,(not set),,58,部長クラス
85877,140724,2026/07/21,,,,,(not set),(not set),,(not set),,57,部長クラス
85878,140725,2026/07/21,ロンザン,2026/07/21,TRUE,2026/07/21,(not set),(not set),,(not set),,59,部長クラス
85879,140726,2026/07/21,ロンザン,2026/07/21,TRUE,2026/07/21,(not set),(not set),,(not set),,46,課長クラス

In [246]:
rzhonkosho_query = """
with HONS as (
with SHOKIS as (
with shoki_base3 as (
with shoki_base2 as (
with shoki_base as (
SELECT
  shk.id,
  shk.tenki_id,
  shk.kohosha_id,
  shk.ap_source,
  layer.name as layer,
  shk.annual_income,
  CASE WHEN syi1.sei_plus IS NULL THEN shk.mendan_tanto
       ELSE syi1.sei_plus END AS mendan_tanto,
  syi2.sei_plus AS ap_kakutokusha,
  shk.kosho_setteibi,
  shk.kosho_yoteibi,
  shk.kosho_jisshibi,
  shk.kosho_seq,
  shk.saikosho_kaisu,
  saikosho_seq,
  valid_flag,
  shk.initial_contact_date,
  DATE_DIFF(shk.kosho_setteibi, LAG(shk.kosho_jisshibi) OVER (PARTITION BY shk.kohosha_id ORDER BY shk.kosho_jisshibi), DAY) AS keikabi
FROM (
  SELECT *,
    FIRST_VALUE(kosho_jisshibi IGNORE NULLS) OVER (PARTITION BY kohosha_id ORDER BY kosho_jisshibi) AS initial_contact_date
  FROM `r-group-bigdata.live_rhs.shokikoshos`
) shk
LEFT JOIN `r-group-bigdata.live_rhs.kohoshas` koho ON shk.kohosha_id = koho.id
LEFT JOIN `r-group-bigdata.live_company.syain` syi1 ON shk.mendan_tanto = syi1.user_id
LEFT JOIN `r-group-bigdata.live_company.syain` syi2 ON shk.ap_kakutoku = syi2.user_id
LEFT JOIN (SELECT 
    code,
    name
  FROM `r-group-bigdata.live_rhs.sys_consts`
  WHERE group_code = 19) consts ON shk.ap_source = consts.code
left join (SELECT 
            group_code,
             code,
             name
            FROM `r-group-bigdata.live_rhs.sys_consts`
            where group_code = 25) layer on shk.max_bushoyakushoku = layer.code
ORDER BY shk.kosho_setteibi
)

  select *,
    LAG(ap_source) OVER (PARTITION BY kohosha_id ORDER BY kosho_setteibi) AS prev_APsource,
  from shoki_base)

  select *,
   CASE WHEN ap_source != prev_APsource THEN 1 ELSE 0
        END AS APS_change
  from shoki_base2)

  select *,
  case when kosho_seq = 1 then 1
        when APS_change = 1 then 1
        when keikabi > 90 then 2
        else 0 end as sai_flg
  from shoki_base3
  order by kosho_setteibi desc
)

SELECT 
  hon.id as honkosho_id,
  hon.anken_id as anken_id,
  an.kohosha_id as kohosha_id,
  koho.tenki_id,
  an.linked_shokikosho_id,
  kgy.tsr_code as tsr_code,
  kgy.name,
  case when consts.name is null then consts2.name
       else consts.name end as AP_source,
  shoki.annual_income,
  shoki.layer,
  initial_contact_date,
  format_date('%Y/%m/%d',shoki.kosho_setteibi) as shoki_setteibi,
  format_date('%Y/%m/%d',shoki.kosho_jisshibi) as shoki_jisshibi,
  format_date('%Y/%m/%d',hon.kosho_setteibi) as hon_setteibi,
  format_date('%Y/%m/%d',hon.kosho_yoteibi) as hon_yoteibi,
  format_date('%Y/%m/%d',hon.kosho_jisshibi) as hon_jisshibi,
  case when syi1.sei_plus is null then hon.kohosha_tanto
  else syi1.sei_plus end as kohosha_tanto,
  syi2.sei_plus as kigyo_tanto,
  hon.kosho_seq as hon_seq,
  shoki.kosho_seq,
  shoki.sai_flg,
  DATE_DIFF(hon.kosho_setteibi, shoki.kosho_jisshibi, DAY) as jisshibi_sa,
  yomi.name as yomi,
  case when yomi2.name is null then yomi.name
       when yomi2.name = yomi.name then yomi2.name
       else yomi2.name end as yomi_final,
  ROUND(tokikessan_uriagedaka/100000,0)as URIAGE,
  consts3.name as yakushoku_class,
  first_mendan.mendan_tanto as first_mendan_tanto
FROM `r-group-bigdata.live_rhs.honkoshos` hon
LEFT JOIN `r-group-bigdata.live_rhs.ankens` an on hon.anken_id = an.id
left join (with yomis_base as (
           SELECT *,
           row_number() over (partition by anken_id order by yomi_torokubi desc) as rn
           FROM `r-group-bigdata.live_rhs.honkosho_yomis`)
           select *
          from yomis_base
          where rn = 1) yomis on an.id = yomis.anken_id
LEFT JOIN SHOKIS shoki on an.linked_shokikosho_id = shoki.id
LEFT JOIN `r-group-bigdata.live_rhs.kigyos` kgy on an.kigyo_id = kgy.id
left join `r-group-bigdata.tsr.company_info` tsr on kgy.tsr_code = tsr.tsr_code
LEFT JOIN `r-group-bigdata.live_rhs.kohoshas` koho on an.kohosha_id = koho.id
LEFT JOIN `r-group-bigdata.live_company.syain` syi1 on hon.kohosha_tanto = syi1.user_id
LEFT JOIN `r-group-bigdata.live_company.syain` syi2 on an.kigyo_tanto = syi2.user_id
left join (select
              shoki.id,
              shoki.kohosha_id,
              case when syi3.sei_plus is null then shoki.mendan_tanto
                   else syi3.sei_plus end as mendan_tanto,
              shoki.kosho_jisshibi
             from `r-group-bigdata.live_rhs.shokikoshos` shoki 
             left join `r-group-bigdata.live_company.syain` syi3 on shoki.mendan_tanto = syi3.user_id
             where kosho_seq = 1) first_mendan on an.kohosha_id = first_mendan.kohosha_id
LEFT JOIN (SELECT code,name
             FROM `r-group-bigdata.live_rhs.sys_consts`
             where group_code = 19) consts on shoki.ap_source = consts.code
LEFT JOIN (SELECT code,name
             FROM `r-group-bigdata.live_rhs.sys_consts`
             where group_code = 19) consts2 on koho.ap_source = consts2.code
left join (SELECT code,name
             FROM `r-group-bigdata.live_rhs.sys_consts`
             where group_code = 9) yomi on hon.yomi = yomi.code
left join (SELECT code,name
             FROM `r-group-bigdata.live_rhs.sys_consts`
             where group_code = 9) yomi2 on yomis.yomi = yomi2.code
left join (SELECT code,name
             FROM `r-group-bigdata.live_rhs.sys_consts`
             where group_code = 10) consts3 on hon.yakushoku_class = consts3.code
-- where hon.kosho_seq = 1
)

select *,
  case when AP_source = '転機社長名鑑' then '転機'
       when AP_source = '人事部経由' then '人事部紹介'
       when AP_source = '顧問名鑑登録　解放者' then '顧問名鑑登録者'
       when AP_source = 'HP反響' then 'その他'
       when AP_source = '上場企業役員DM' then 'その他'
       when AP_source = '社外取締役名鑑　候補者' then '顧問名鑑登録者'
       when AP_source = 'Gアポ' then 'その他'
       else AP_source end as APsource,

  case when shoki_jisshibi is null then 2
       when jisshibi_sa > 90 then 2
       else sai_flg end as sai_flg2 
from HONS
where AP_source = "転機社長名鑑"
-- and hon_setteibi >= "2025/03/27"
order by anken_id
"""
client = bigquery.Client(credentials=credentials, project=credentials.project_id)
honkosho = client.query(rzhonkosho_query).result().to_dataframe()

In [247]:
honkosho["tenki_id"] = honkosho["tenki_id"].astype(str)
honkosho = pd.merge(honkosho,adinfoB,how="left", on="tenki_id")

In [248]:
honkosho = honkosho[["tenki_id","登録日時","hon_setteibi","hon_jisshibi","参照元/メディア","キャンペーン","広告ID","KWD","sai_flg2"]]

In [249]:
honkosho["tenki_id"] = honkosho["tenki_id"].str.replace('<NA>', '')
honkosho["登録日時"] = honkosho["登録日時"].str.replace('NaN', '')
honkosho["hon_jisshibi"] = honkosho["hon_jisshibi"].str.replace('None', '')
honkosho["参照元/メディア"] = honkosho["参照元/メディア"].str.replace('NaN', '')
honkosho["キャンペーン"] = honkosho["キャンペーン"].str.replace('NaN', '')
honkosho["広告ID"] = honkosho["広告ID"].str.replace('NaN', '')
honkosho["KWD"] = honkosho["KWD"].str.replace('NaN', '')

In [250]:
honkosho.dtypes

tenki_id        object
登録日時            object
hon_setteibi    object
hon_jisshibi    object
参照元/メディア        object
キャンペーン          object
広告ID            object
KWD             object
sai_flg2         Int64
dtype: object

In [251]:
honkosho.replace([np.inf, -np.inf], np.nan, inplace=True)
honkosho.fillna('', inplace=True)
honkosho = honkosho.values.tolist()

In [252]:
#成約単価シートにコピペ
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly',
          'https://www.googleapis.com/auth/spreadsheets']
json_path = r"Z:\Users\suehara\Documents\python\analysis\python_ss\credentials.json"
service = ps.get_auth(SCOPES,json_path)
SPREADSHEET_ID = '1Mvqe8nLhdiT9acCMA4cP-4MH5X4GmYPiC9OSqHTEHtk'
Sheet_NAME = 'rzdata!J'
Sheet_row = "3"
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,honkosho,service)

In [253]:
#NMのシートにコピペ
SPREADSHEET_ID = '1d1uYQMCIhJGMlUe4S8m56Bd_ZS4_V-FUEtPjUlgpn9Y'
Sheet_NAME = 'rzdata!J'
Sheet_row = "3"
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,honkosho,service)

In [254]:
#ZEALSのシートにコピペ
SPREADSHEET_ID = '1EglGY_Lf1kvHqZTpow4F2ksD20xD9J8G1oaMIjtyj78'
Sheet_NAME = 'rzdata!J'
Sheet_row = "3"
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,honkosho,service)

In [255]:
#CAのシートにコピペ
SPREADSHEET_ID = '1fVbpOYwIRsbW69EDsbJlTJwJVPTexi8RoMd3ahiO-IA'
Sheet_NAME = 'data!J'
Sheet_row = "3"
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,honkosho,service)

## SCKPI

In [256]:
adinfoC = adinfo.copy()

In [257]:
sckpi_query = """
WITH
-- =================================================================
-- データ結合と基本加工セクション
-- 必要なテーブルを結合し、基本的なカラムを計算する
-- =================================================================
base_data AS (
  SELECT
    rc.tenki_id,
    can.ap_kakutoku AS shokikosho_setteibi,
    rc.first_nmen_date AS first_jisshi_date,
    can.nmen_zisshi AS shokikosho_jisshibi,
    -- COALESCE関数を使い、繰り返しが多いCASE文を簡潔に書き換え
    COALESCE(
      com.settei8, com.settei7, com.settei6, com.settei5,
      com.settei4, com.settei3, com.settei2, com.settei1
    ) AS honkosho_setteibi,
    COALESCE(
      com.zisshi8, com.zisshi7, com.zisshi6, com.zisshi5,
      com.zisshi4, com.zisshi3, com.zisshi2, com.zisshi1
    ) AS honkosho_jissibi,
    com.seiyaku,
    can.kouhosya_tantou AS kohosha_tanto,
    can.client_tantou AS kigyo_tanto,
    can.mendan_tantou AS mendan_tanto,
    can.ap_source,
    CASE
      WHEN can.zisshi LIKE 'キャンセル%' THEN 'CXL'
      WHEN can.zisshi LIKE '%実施%' THEN '実施'
      ELSE '-'
    END AS CXL_status
  FROM
    `r-group-bigdata.live_sugarcrm52.rc_race_candidate_management` AS rc
    LEFT JOIN `r-group-bigdata.live_saltcrm.candidate` AS can ON can.sugarid = rc.candidate_no
    LEFT JOIN `r-group-bigdata.live_saltcrm.company` AS com ON com.candidate_id = can.id
  WHERE
    rc.tenki_id IS NOT NULL
    AND rc.deleted = 0
)

-- =================================================================
-- 最終的な集計と出力
-- ウィンドウ関数を用いて登場回数をカウントする
-- =================================================================
SELECT
  *,
  -- tenki_idごとに、shokikosho_setteibi（設定日）の昇順で登場回数をカウント
  ROW_NUMBER() OVER (PARTITION BY tenki_id ORDER BY shokikosho_setteibi) AS sai_flg
FROM
  base_data
where shokikosho_setteibi >= "2019-10-01"
and (ap_source = "転機" or ap_source = "マッチング")
ORDER BY
  shokikosho_setteibi;

"""

client = bigquery.Client(credentials=credentials, project=credentials.project_id)
sckpi = client.query(sckpi_query).result().to_dataframe()

In [258]:
adinfoC = adinfoC.query('フリ先 == "レイノス"')
adinfoC = adinfoC[["tenki_id","登録日時","フリ先","手上げ日付","参照元/メディア","キャンペーン","広告ID","KWD"]]

In [259]:
adinfoC

,tenki_id,登録日時,フリ先,手上げ日付,参照元/メディア,キャンペーン,広告ID,KWD
4,8539,2017/09/15,レイノス,2017/09/15,fb_ad / display,(not set),(not set),(not set)
5,9502,2017/10/05,レイノス,2017/10/05,yahoo_Ten / cpc_CA,(not set),(not set),(not set)
7,12216,2017/12/13,レイノス,2017/12/13,google / organic,(not set),(not set),(not provided)
8,12406,2017/12/20,レイノス,2017/12/20,google_Saiyo / cpc_Area,(not set),(not set),(not set)
9,12511,2017/12/24,レイノス,2017/12/24,google_Saiyo / cpc_CA,(not set),(not set),(not set)
...,...,...,...,...,...,...,...,...
85543,140390,2026/06/28,レイノス,2026/06/30,"zeals_ad,zeals / chat_cpf",shot_over2y,(not set),(not set)
85708,140555,2026/07/10,レイノス,2026/07/13,facebook / display,CP02,ADS05,(not set)
85749,140596,2026/07/12,レイノス,2026/07/14,facebookcasm / display,CP02,ADS09,(not set)
85754,140601,2026/07/13,レイノス,2026/07/14,,,,
85787,140634,2026/07/15,レイノス,2026/07/17,google / organic,(organic),(not set),(not set)

In [260]:
sckpi = sckpi.rename(columns={"tenki_id":"ID"})
sckpi = sckpi.rename(columns={"ID":"tenki_id"})
sckpi["tenki_id"] = sckpi["tenki_id"].astype(str)
sckpi["shokikosho_setteibi"] = sckpi["shokikosho_setteibi"].astype(str)
sckpi["first_jisshi_date"] = sckpi["first_jisshi_date"].astype(str)
sckpi["shokikosho_jisshibi"] = sckpi["shokikosho_jisshibi"].astype(str)
sckpi["honkosho_setteibi"] = sckpi["honkosho_setteibi"].astype(str)
sckpi["honkosho_jissibi"] = sckpi["honkosho_jissibi"].astype(str)
sckpi["seiyaku"] = sckpi["seiyaku"].astype(str)

In [261]:
sckpi = pd.merge(sckpi,adinfoC,how="left",on="tenki_id")

In [262]:
sckpi["登録日時"] = sckpi["登録日時"].str.replace('NaN', '')
sckpi["フリ先"] = sckpi["フリ先"].str.replace('NaN', '')
sckpi["手上げ日付"] = sckpi["手上げ日付"].str.replace('NaN', '')
sckpi["参照元/メディア"] = sckpi["参照元/メディア"].str.replace('NaN', '')
sckpi["キャンペーン"] = sckpi["キャンペーン"].str.replace('NaN', '')
sckpi["広告ID"] = sckpi["広告ID"].str.replace('NaN', '')
sckpi["KWD"] = sckpi["KWD"].str.replace('NaN', '')

sckpi["first_jisshi_date"] = sckpi["first_jisshi_date"].str.replace('NaT', '')
sckpi["shokikosho_jisshibi"] = sckpi["shokikosho_jisshibi"].str.replace('NaT', '')
sckpi["honkosho_setteibi"] = sckpi["honkosho_setteibi"].str.replace('NaT', '')
sckpi["honkosho_jissibi"] = sckpi["honkosho_jissibi"].str.replace('NaT', '')
sckpi["seiyaku"] = sckpi["seiyaku"].str.replace('NaT', '')

In [263]:
sckpi_nm = sckpi.drop(columns=['kohosha_tanto','kigyo_tanto','mendan_tanto','CXL_status'])

In [264]:
sckpi

,tenki_id,shokikosho_setteibi,first_jisshi_date,shokikosho_jisshibi,honkosho_setteibi,honkosho_jissibi,seiyaku,kohosha_tanto,kigyo_tanto,mendan_tanto,ap_source,CXL_status,sai_flg,登録日時,フリ先,手上げ日付,参照元/メディア,キャンペーン,広告ID,KWD
0,45935,2019-10-01,2019-10-10,2019-10-10,None,None,None,樋口貴治,None,樋口貴治,転機,実施,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,46091,2019-10-01,2019-10-31,2019-10-31,None,None,None,増田 智洋,None,増田 智洋,転機,実施,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,46183,2019-10-01,2019-10-10,2019-10-10,2019-10-17,2019-10-26,None,中川 美帆,井上徹,中川 美帆,転機,実施,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,46213,2019-10-01,2019-10-07,2019-10-07,None,None,None,花田和明,None,花田和明,転機,実施,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,46246,2019-10-01,2019-10-07,2019-10-07,None,None,None,加藤香保,None,加藤香保,転機,実施,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14665,47162,2026-07-22,None,None,None,None,None,川島花,None,川島花,転機,-,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14666,97217,3000-01-01,None,1970-01-01,1970-01-01,1970-01-01,2023-05-31,田宮倫太郎,樋口利次,岩瀬一樹,マッチング,実施,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14667,101893,3000-01-01,None,1970-01-01,1970-01-01,1970-01-01,2023-03-10,清水泰名,菅沼涼,菅沼涼,マッチング,実施,2,2023/01/20,レイノス,2023/01/23,google / cpc,G検索_03_一般,(not set),商社 転職
14668,103020,3000-01-01,None,1970-01-01,1970-01-01,1970-01-01,2023-03-29,松本翔,佐々木啓晃,水野真,マッチング,実施,1,2023/03/08,レイノス,2023/05/02,#N/A,#N/A,#N/A,#N/A
14669,74725,3000-01-01,2020-12-29,1970-01-01,1970-01-01,1970-01-01,2023-04-28,森永祐司,森永祐司,紺田隆,マッチング,実施,3,2020/12/26,レイノス,2020/12/28,fb_ad / display,fb-adset-ace4,(not set),(not set)

In [265]:
sckpi.replace([np.inf, -np.inf], np.nan, inplace=True)
sckpi.fillna('', inplace=True)

sckpi = sckpi.values.tolist()

In [266]:
sckpi_nm.replace([np.inf, -np.inf], np.nan, inplace=True)
sckpi_nm.fillna('', inplace=True)

sckpi_nm = sckpi_nm.values.tolist()

In [267]:
##成約単価シートにコピペ
SPREADSHEET_ID = '1Mvqe8nLhdiT9acCMA4cP-4MH5X4GmYPiC9OSqHTEHtk'
Sheet_NAME = 'scdata!A'
Sheet_row = "2"
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,sckpi,service)

In [268]:
##NMのシートにコピペ
SPREADSHEET_ID = '1d1uYQMCIhJGMlUe4S8m56Bd_ZS4_V-FUEtPjUlgpn9Y'
Sheet_NAME = 'scdata!A'
Sheet_row = "2"
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,sckpi_nm,service)

In [269]:
#CAのシートにコピペ
SPREADSHEET_ID = '1fVbpOYwIRsbW69EDsbJlTJwJVPTexi8RoMd3ahiO-IA'
Sheet_NAME = 'scdata!A'
Sheet_row = "3"
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,sckpi_nm,service)

## 成約データ

In [270]:
# 最後のIDを取得する
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly',
          'https://www.googleapis.com/auth/spreadsheets']
json_path = r"Z:\Users\suehara\Documents\python\analysis\python_ss\credentials.json"
service = ps.get_auth(SCOPES,json_path)
SPREADSHEET_ID = '1qtTngN03WSZ_JjZovhNVh6bd1uc_Eh8tRP5Hp9yWSNc'
Sheet_NAME = 'yomihyo!A'
Sheet_row = ":T"
RANGE_NAME = Sheet_NAME+Sheet_row

seiyaku = ps.get_ss(SPREADSHEET_ID,RANGE_NAME,service)

# データ取得処理の呼び出し
# seiyaku = fetch_spreadsheet(service, SPREADSHEET_ID, RANGE_NAME)

In [271]:
adinfoB

,tenki_id,登録日時,フリ先,手上げ日付,本手上げ,KN共有日,参照元/メディア,キャンペーン,広告ID,KWD,,年齢,役職
1,1070,2016/09/17,ロンザン,2020/05/20,ZOOM,,,,,,,49,部長クラス
2,2748,2017/02/06,ロンザン,2017/02/06,,,,,,,,59,役員クラス
3,7024,2017/08/07,ロンザン,2017/08/07,,,google_SHIMEI / cpc,(not set),(not set),(not set),,55,リーダークラス
4,8539,2017/09/15,レイノス,2017/09/15,,,fb_ad / display,(not set),(not set),(not set),,35,リーダークラス
5,9502,2017/10/05,レイノス,2017/10/05,0,,yahoo_Ten / cpc_CA,(not set),(not set),(not set),,45,役員クラス
...,...,...,...,...,...,...,...,...,...,...,...,...,...
85875,140722,2026/07/20,ロンザン,2026/07/21,TRUE,2026/07/21,facebookcasm / display,CP02,ADS11,(not set),F00265,51,部長クラス
85876,140723,2026/07/21,ロンザン,2026/07/21,TRUE,2026/07/21,(not set),(not set),,(not set),,58,部長クラス
85877,140724,2026/07/21,,,,,(not set),(not set),,(not set),,57,部長クラス
85878,140725,2026/07/21,ロンザン,2026/07/21,TRUE,2026/07/21,(not set),(not set),,(not set),,59,部長クラス
85879,140726,2026/07/21,ロンザン,2026/07/21,TRUE,2026/07/21,(not set),(not set),,(not set),,46,課長クラス

In [272]:
seiyaku

,転機ID,案件ID,登録日,部署,計上日,,年齢,前職年収,kohosha_id,売上金額,獲得P,基準年収,linkedshokikoushoID,初期実施日,本交渉設定日,本交渉予定日,本交渉実施日,候補者担当,企業担当,sai_flg
1,-,1736,-,ロンザン,2017-10-17 0:00:00,2017-10-17 0:00:00,60,1200,3632,571.532,60.01086,985.4,2249,2017/08/23,2017-09-09 0:00:00,2017-09-12 0:00:00,2017-09-12 0:00:00,長崎文,角田隆,1
2,8871,1815,-,ロンザン,2017-10-31 0:00:00,2017-10-31 0:00:00,54,2040,4111,754.464,79.21872,1300.8,2657,2017/09/28,2017-10-12 0:00:00,2017-10-20 0:00:00,2017-10-20 0:00:00,大矢裕,山崎弘,1
3,-,1546,-,ロンザン,2017-11-13 0:00:00,2017-11-13 0:00:00,53,800,2392,478.5928,50.252244,825.16,1114,2017/05/12,2017-07-27 0:00:00,2017-08-23 0:00:00,2017-08-23 0:00:00,宇野憲,石井達,1
4,-,1817,-,ロンザン,2017-11-21 0:00:00,2017-11-21 0:00:00,61,2000,3661,1350.124,141.76302,2327.8,2280,2017/08/30,2017-10-12 0:00:00,2017-10-19 0:00:00,2017-10-19 0:00:00,服部圭,林宣,1
5,-,1865,-,ロンザン,2017-11-27 0:00:00,2017-11-27 0:00:00,53,1050,4351,432,45.36,900,2878,2017/10/19,2017-10-20 0:00:00,2017-10-30 0:00:00,2017-10-30 0:00:00,宮崎佳,増田智,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,137293,29798,2025/12/14,ロンザン,2026-06-30 0:00:00,-,52,1250,72892,978.1716,202.041,1417.64,88041,2026/02/09,2026-05-07 0:00:00,2026-05-11 0:00:00,2026-05-11 0:00:00,小池悠,細川諒,1
1479,-,29334,-,ロンザン,2026-06-30 0:00:00,-,61,1100,61413,335,69.194,335,-1,,2026-05-15 0:00:00,2026-05-22 0:00:00,2026-05-22 0:00:00,五十嵐り,柘植一,2
1480,139777,29409,2026/05/11,ロンザン,2026-06-30 0:00:00,-,55,1000,75832,983.94,203.233,1426,91863,2026/05/18,2026-05-22 0:00:00,2026-06-08 0:00:00,-,小幡八,簾内俊,1
1481,138122,28546,2026/02/11,ロンザン,2026-07-14 0:00:00,2026-04-28 0:00:00,61,1500,73868,901.4834,175.248,1502.4724,89338,2026/02/26,2026-02-27 0:00:00,2026-03-03 0:00:00,2026-03-03 0:00:00,小川弘,高橋優２,1
1482,122881,28587,2024/10/30,ロンザン,2026-07-22 0:00:00,2026-07-06 0:00:00,61,3600,59695,828.00,160.963,1200,81555,2025/07/16,2026-03-03 0:00:00,2026-03-13 0:00:00,2026-03-13 0:00:00,前田崚,岸靖,2

In [273]:
adinfoB = adinfoB.rename(columns={"tenki_id":"転機ID"})

seiyaku = pd.merge(seiyaku,adinfoB,how="left", on="転機ID")

In [274]:
seiyaku["移籍年収"] = ""
seiyaku = seiyaku[["転機ID","登録日","計上日","獲得P","参照元/メディア","キャンペーン","広告ID","KWD","前職年収","移籍年収","売上金額","sai_flg"]]

In [275]:
seiyaku

,転機ID,登録日,計上日,獲得P,参照元/メディア,キャンペーン,広告ID,KWD,前職年収,移籍年収,売上金額,sai_flg
0,-,-,2017-10-17 0:00:00,60.01086,NaN,NaN,NaN,NaN,1200,,571.532,1
1,8871,-,2017-10-31 0:00:00,79.21872,NaN,NaN,NaN,NaN,2040,,754.464,1
2,-,-,2017-11-13 0:00:00,50.252244,NaN,NaN,NaN,NaN,800,,478.5928,1
3,-,-,2017-11-21 0:00:00,141.76302,NaN,NaN,NaN,NaN,2000,,1350.124,1
4,-,-,2017-11-27 0:00:00,45.36,NaN,NaN,NaN,NaN,1050,,432,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1477,137293,2025/12/14,2026-06-30 0:00:00,202.041,facebook / display,CP01,ADS02,(not set),1250,,978.1716,1
1478,-,-,2026-06-30 0:00:00,69.194,NaN,NaN,NaN,NaN,1100,,335,2
1479,139777,2026/05/11,2026-06-30 0:00:00,203.233,yahoo / display,y05_income,423,(not set),1000,,983.94,1
1480,138122,2026/02/11,2026-07-14 0:00:00,175.248,(direct) / (none),(direct),(not set),(not set),1500,,901.4834,1
1481,122881,2024/10/30,2026-07-22 0:00:00,160.963,m.facebook.com / referral,(referral),(not set),(not set),3600,,828.00,2

In [276]:
seiyaku["参照元/メディア"] = seiyaku["参照元/メディア"].str.replace('NaN', '')
seiyaku["キャンペーン"] = seiyaku["キャンペーン"].str.replace('NaN', '')
seiyaku["広告ID"] = seiyaku["広告ID"].str.replace('NaN', '')
seiyaku["KWD"] = seiyaku["KWD"].str.replace('NaN', '')
seiyaku["売上金額"] = seiyaku["売上金額"].str.replace('NaN', '')

In [277]:
seiyaku

,転機ID,登録日,計上日,獲得P,参照元/メディア,キャンペーン,広告ID,KWD,前職年収,移籍年収,売上金額,sai_flg
0,-,-,2017-10-17 0:00:00,60.01086,NaN,NaN,NaN,NaN,1200,,571.532,1
1,8871,-,2017-10-31 0:00:00,79.21872,NaN,NaN,NaN,NaN,2040,,754.464,1
2,-,-,2017-11-13 0:00:00,50.252244,NaN,NaN,NaN,NaN,800,,478.5928,1
3,-,-,2017-11-21 0:00:00,141.76302,NaN,NaN,NaN,NaN,2000,,1350.124,1
4,-,-,2017-11-27 0:00:00,45.36,NaN,NaN,NaN,NaN,1050,,432,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1477,137293,2025/12/14,2026-06-30 0:00:00,202.041,facebook / display,CP01,ADS02,(not set),1250,,978.1716,1
1478,-,-,2026-06-30 0:00:00,69.194,NaN,NaN,NaN,NaN,1100,,335,2
1479,139777,2026/05/11,2026-06-30 0:00:00,203.233,yahoo / display,y05_income,423,(not set),1000,,983.94,1
1480,138122,2026/02/11,2026-07-14 0:00:00,175.248,(direct) / (none),(direct),(not set),(not set),1500,,901.4834,1
1481,122881,2024/10/30,2026-07-22 0:00:00,160.963,m.facebook.com / referral,(referral),(not set),(not set),3600,,828.00,2

In [278]:
seiyaku_tk = seiyaku.copy()
seiyaku_tk.replace([np.inf, -np.inf], np.nan, inplace=True)
seiyaku_tk.fillna('', inplace=True)
seiyaku_tk = seiyaku_tk.values.tolist()

In [279]:
##成約単価シートにコピペ
SPREADSHEET_ID = '1Mvqe8nLhdiT9acCMA4cP-4MH5X4GmYPiC9OSqHTEHtk'
Sheet_NAME = 'rzdata!S'
Sheet_row = "3"
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,seiyaku_tk,service)

In [280]:
#NMのシートにコピペ
SPREADSHEET_ID = '1d1uYQMCIhJGMlUe4S8m56Bd_ZS4_V-FUEtPjUlgpn9Y'
Sheet_NAME = 'rzdata!S'
Sheet_row = "3"
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,seiyaku_tk,service)

In [281]:
#ZEALSのシートにコピペ
SPREADSHEET_ID = '1EglGY_Lf1kvHqZTpow4F2ksD20xD9J8G1oaMIjtyj78'
Sheet_NAME = 'rzdata!S'
Sheet_row = "3"
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,seiyaku_tk,service)

In [282]:
#CAのシートにコピペ
SPREADSHEET_ID = '1fVbpOYwIRsbW69EDsbJlTJwJVPTexi8RoMd3ahiO-IA'
Sheet_NAME = 'data!S'
Sheet_row = "3"
RANGE_NAME = Sheet_NAME+Sheet_row
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,seiyaku_tk,service)

### CR別パフォーマンスを更新

In [283]:
#当月の初日を取得
now = datetime.datetime.now()
def get_first_date(year,month):
    return datetime.date(year, month, 1)
firstday = get_first_date(now.year,now.month)
firstday_minus_60 = firstday - datetime.timedelta(days=30)
firstday_minus_60 = firstday_minus_60.strftime("%Y-%m-%d")
firstday_minus_60

'2026-06-01'

## 広告情報取得

In [284]:
#最後のIDを取得する
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly',
          'https://www.googleapis.com/auth/spreadsheets']
json_path = r"Z:\Users\suehara\Documents\python\analysis\python_ss\credentials.json"
service = ps.get_auth(SCOPES,json_path)
SPREADSHEET_ID = '14vXxjcdlyY463QjrtEnCw7pJ0oLStXZD8Q42IdW2Zd4'
Sheet_NAME = '候補者マスタ!A'
Sheet_row = ":M"
RANGE_NAME = Sheet_NAME+Sheet_row
adinfo = ps.get_ss(SPREADSHEET_ID,RANGE_NAME,service)

In [285]:
adinfoA = adinfo.copy()

In [286]:
adinfoA.dtypes

tenki_id    object
登録日時        object
フリ先         object
手上げ日付       object
本手上げ        object
KN共有日       object
参照元/メディア    object
キャンペーン      object
広告ID        object
KWD         object
            object
年齢          object
役職          object
dtype: object

In [287]:
#IDのデータ型をint64に変換
adinfoA['tenki_id'] = pd.to_numeric(adinfoA['tenki_id'], errors='coerce')
adinfoA['tenki_id'] = adinfoA['tenki_id'].fillna(0)
adinfoA['tenki_id'] = adinfoA['tenki_id'].astype('int64')

# `登録日時`列が文字列型（str）の場合、以下のコードでdatetime形式に変換します
adinfoA['登録日時'] = pd.to_datetime(adinfoA['登録日時'])

# 特定の日付以降のデータのみを抽出します
adinfoA = adinfoA[adinfoA['登録日時'] >= firstday_minus_60]

# 'フリ先'が'ロンザン'または'レイノス'と一致する場合、'1'に変換
adinfoA.loc[adinfoA['フリ先'].isin(['ロンザン', 'レイノス']), 'フリ先'] = '1'

# 'フリ先'が'送信NG'と一致する場合、空白に変換
adinfoA.loc[adinfoA['フリ先'] == '送信NG', 'フリ先'] = ''

# '本手上げ'が'TRUE'なら'1'、'FALSE'なら'0'に変換
adinfoA.loc[adinfoA['本手上げ'] == 'TRUE', '本手上げ'] = '1'
adinfoA.loc[adinfoA['本手上げ'] == 'FALSE', '本手上げ'] = '0'

In [288]:
adinfoA

,tenki_id,登録日時,フリ先,手上げ日付,本手上げ,KN共有日,参照元/メディア,キャンペーン,広告ID,KWD,,年齢,役職
85185,140032,2026-06-01,1,2026/06/01,1,,google / organic,(organic),(not set),(not set),(not provided),43,役員クラス
85186,140033,2026-06-01,1,2026/06/02,1,2026/06/02,facebookcasm / display,CP02,ADS09,(not set),F00246,59,課長クラス
85187,140034,2026-06-01,,,,,bing / organic,(organic),(not set),(not set),(not provided),60,課長クラス
85188,140035,2026-06-01,1,2026/06/02,1,,yahoo / paidsearch,y01_brand_single,1361,(not set),y01_brand_single,55,役員クラス
85189,140036,2026-06-01,1,2026/06/02,1,2026/06/02,,,,,,62,役員クラス
...,...,...,...,...,...,...,...,...,...,...,...,...,...
85875,140722,2026-07-20,1,2026/07/21,1,2026/07/21,facebookcasm / display,CP02,ADS11,(not set),F00265,51,部長クラス
85876,140723,2026-07-21,1,2026/07/21,1,2026/07/21,(not set),(not set),,(not set),,58,部長クラス
85877,140724,2026-07-21,,,,,(not set),(not set),,(not set),,57,部長クラス
85878,140725,2026-07-21,1,2026/07/21,1,2026/07/21,(not set),(not set),,(not set),,59,部長クラス
85879,140726,2026-07-21,1,2026/07/21,1,2026/07/21,(not set),(not set),,(not set),,46,課長クラス

## 登録情報取得

In [289]:
# クエリの一例です。ご自身の実行したいクエリに書き換えて下さい。
tkuserinfo_query = f"""
select
	inf.id,
	format_date('%Y/%m/%d',inf.created_at) as created_at,
	concat(trim(replace(inf.shi,'　',' ')),trim(replace(inf.mei,'　',' '))) as name,
	inf.seibetu,
  concat(inf.birth_year,"/",inf.birth_month,"/",inf.birth_day) as birthday,
  extract(year from inf.created_at)-inf.birth_year as age,
	inf.email,
	inf.mob_tel,
	inf.comp_name,
	inf.gyousyu1,
	inf.jobcat,
	inf.syokusyu1,
	inf.layer,
	inf.income,
  inf.management_num1,
	inf.change_job,
	concat(corp_from_year1,"/",corp_from_month1,"~",
	       ifnull(cast(corp_to_year1 as string),""),"/",ifnull(cast(corp_to_month1 as string),"")) as zaiseki_kikan,
  inf.pref,
	inf.work_pref,
	inf.wish_pref,
	inf.moving,
	inf.kanou_jiki,
	format_date('%Y/%m/%d',dt.keireki_ja_date) as shokureki_upload_date
from
	`r-group-bigdata.live_tenki.user_info` inf
left join `r-group-bigdata.live_tenki.user_detail` dt on inf.id = dt.id 
where
    created_at >= date '{firstday_minus_60}'
order by id
"""
client = bigquery.Client(credentials=credentials, project=credentials.project_id)
tkuserinfo = client.query(tkuserinfo_query).result().to_dataframe()
tkuserinfo = tkuserinfo.rename(columns={"id":"ID"})

In [290]:
adinfoA.columns

Index(['tenki_id', '登録日時', 'フリ先', '手上げ日付', '本手上げ', 'KN共有日', '参照元/メディア',
       'キャンペーン', '広告ID', 'KWD', '', '年齢', '役職'],
      dtype='object')

In [291]:
adinfoA = adinfoA.rename(columns={"tenki_id":"ID"})
ALL_data = pd.merge(adinfoA,tkuserinfo,how='left',on='ID')
ALL_data = ALL_data[["ID","登録日時","フリ先","手上げ日付","本手上げ","参照元/メディア","キャンペーン",
                     "広告ID","KWD","年齢","income","役職","pref","gyousyu1","jobcat","syokusyu1","change_job"]]

In [292]:
ALL_data

,ID,登録日時,フリ先,手上げ日付,本手上げ,参照元/メディア,キャンペーン,広告ID,KWD,年齢,income,役職,pref,gyousyu1,jobcat,syokusyu1,change_job
0,140032,2026-06-01,1,2026/06/01,1,google / organic,(organic),(not set),(not set),43,2000～2999万円,役員クラス,東京都,小売・流通,経営(役員・CxO）/経営企画,経営者・CEO・COO等,4回（5社経験）
1,140033,2026-06-01,1,2026/06/02,1,facebookcasm / display,CP02,ADS09,(not set),59,800～899万円,課長クラス,愛知県,自動車,管理部門,内部監査,4回（5社経験）
2,140034,2026-06-01,,,,bing / organic,(organic),(not set),(not set),60,400～499万円,課長クラス,東京都,その他,専門職（士業）,その他専門職,転職経験なし
3,140035,2026-06-01,1,2026/06/02,1,yahoo / paidsearch,y01_brand_single,1361,(not set),55,1200～1299万円,役員クラス,東京都,外食,経営(役員・CxO）/経営企画,新規事業企画,2回（3社経験）
4,140036,2026-06-01,1,2026/06/02,1,,,,,62,1500～1599万円,役員クラス,千葉県,サービス,経営(役員・CxO）/経営企画,その他会社経営に携わる職種,3回（4社経験）
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
690,140722,2026-07-20,1,2026/07/21,1,facebookcasm / display,CP02,ADS11,(not set),51,1700～1799万円,部長クラス,東京都,金融,営業,営業・企画営業（法人対象）,2回（3社経験）
691,140723,2026-07-21,1,2026/07/21,1,(not set),(not set),,(not set),58,1000～1099万円,部長クラス,東京都,電子部品・半導体,営業,営業・企画営業（法人個人問わず海外営業）,2回（3社経験）
692,140724,2026-07-21,,,,(not set),(not set),,(not set),57,1100～1199万円,部長クラス,東京都,電子部品・半導体,経営(役員・CxO）/経営企画,その他会社経営に携わる職種,1回（2社経験）
693,140725,2026-07-21,1,2026/07/21,1,(not set),(not set),,(not set),59,1100～1199万円,部長クラス,神奈川県,運輸・倉庫,管理部門,国際業務・貿易事務,転職経験なし
694,140726,2026-07-21,1,2026/07/21,1,(not set),(not set),,(not set),46,1100～1199万円,課長クラス,東京都,化学・石油,営業,営業・企画営業（法人対象）,2回（3社経験）

## 各種シートに貼り付け

In [293]:
#NMシートを取得
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly',
          'https://www.googleapis.com/auth/spreadsheets']
json_path = r"Z:\Users\suehara\Documents\python\analysis\python_ss\credentials.json"
service = ps.get_auth(SCOPES,json_path)
SPREADSHEET_ID_NM = '1YRjsfJ76yfAnhoyTlsvcXVKZhmmcvkNwpApf9iubByc'
Sheet_NAME = 'サマリー!A'
Sheet_row = ":A"
RANGE_NAME = Sheet_NAME+Sheet_row
recentID_NM = ps.get_ss(SPREADSHEET_ID_NM,RANGE_NAME,service)

#CAシートを取得
SPREADSHEET_ID_CA = '1fVbpOYwIRsbW69EDsbJlTJwJVPTexi8RoMd3ahiO-IA'
Sheet_NAME = 'サマリー!A'
Sheet_row = ":A"
RANGE_NAME = Sheet_NAME+Sheet_row
recentID_CA = ps.get_ss(SPREADSHEET_ID_CA,RANGE_NAME,service)

#GAXシートを取得
SPREADSHEET_ID_GAX = '1JxBS0dT8nR_o_ehqVdlKYx3iD1jEMIaQPXWl6wJIXJk'
Sheet_NAME = '手上げデータ!A'
Sheet_row = ":A"
RANGE_NAME = Sheet_NAME+Sheet_row
recentID_GAX = ps.get_ss(SPREADSHEET_ID_GAX,RANGE_NAME,service)

In [294]:
#データを入力するセルを特定
recentID_NM['転機ID'] =recentID_NM['転機ID'].astype('int64')
recentID_CA['ID'] =recentID_CA['ID'].astype('int64')
recentID_GAX['ID'] =recentID_GAX['ID'].astype('int64')
matching_index_NM = recentID_NM[recentID_NM["転機ID"] == ALL_data['ID'][0]].index
matching_index_CA = recentID_CA[recentID_CA["ID"] == ALL_data['ID'][0]].index
matching_index_GAX = recentID_GAX[recentID_GAX["ID"] == ALL_data['ID'][0]].index

In [295]:
matching_index_NM

Index([], dtype='int64')

In [296]:
# matching_index_NM の中身が1つ以上あるか確認します
if len(matching_index_NM) > 0:
    print(matching_index_NM[0] + 1)
else:
    print("NM: 条件に一致するデータが見つかりませんでした。")

# matching_index_CA の確認
if len(matching_index_CA) > 0:
    print(matching_index_CA[0] + 1)
else:
    print("CA: 条件に一致するデータが見つかりませんでした。")

# matching_index_GAX の確認
if len(matching_index_GAX) > 0:
    print(matching_index_GAX[0] + 1)
else:
    print("GAX: 条件に一致するデータが見つかりませんでした。")

NM: 条件に一致するデータが見つかりませんでした。
CA: 条件に一致するデータが見つかりませんでした。
GAX: 条件に一致するデータが見つかりませんでした。

In [297]:
ALL_data["ID"] = ALL_data["ID"].astype(str) 
ALL_data["登録日時"] = ALL_data["登録日時"].astype(str)

# infをNaNに置き換え
ALL_data.replace([np.inf, -np.inf], np.nan, inplace=True)

# NaNをNoneに置き換え
ALL_data = ALL_data.where(pd.notnull(ALL_data), None)


ALL_data = ALL_data.values.tolist()

In [298]:
ALL_data

[['140032',
  '2026-06-01',
  '1',
  '2026/06/01',
  '1',
  'google / organic',
  '(organic)',
  '(not set)',
  '(not set)',
  '43',
  '2000～2999万円',
  '役員クラス',
  '東京都',
  '小売・流通',
  '経営(役員・CxO）/経営企画',
  '経営者・CEO・COO等',
  '4回（5社経験）'],
 ['140033',
  '2026-06-01',
  '1',
  '2026/06/02',
  '1',
  'facebookcasm / display',
  'CP02',
  'ADS09',
  '(not set)',
  '59',
  '800～899万円',
  '課長クラス',
  '愛知県',
  '自動車',
  '管理部門',
  '内部監査',
  '4回（5社経験）'],
 ['140034',
  '2026-06-01',
  '',
  '',
  '',
  'bing / organic',
  '(organic)',
  '(not set)',
  '(not set)',
  '60',
  '400～499万円',
  '課長クラス',
  '東京都',
  'その他',
  '専門職（士業）',
  'その他専門職',
  '転職経験なし'],
 ['140035',
  '2026-06-01',
  '1',
  '2026/06/02',
  '1',
  'yahoo / paidsearch',
  'y01_brand_single',
  '1361',
  '(not set)',
  '55',
  '1200～1299万円',
  '役員クラス',
  '東京都',
  '外食',
  '経営(役員・CxO）/経営企画',
  '新規事業企画',
  '2回（3社経験）'],
 ['140036',
  '2026-06-01',
  '1',
  '2026/06/02',
  '1',
  '',
  '',
  '',
  '',
  '62',
  '1500～1599万円',
  '役員クラス',
  '千葉県',
  'サービス',
  '経営(役員・CxO）/経営企画',
  'その他会社経営に携わる職種',
  '3回（4社経験）'],
 ['140037',
  '2026-06-01',
  '1',
  '2026/06/03',
  '0',
  'google / cpc',
  'G検索_01_指名',
  '(not set)',
  '転機',
  '39',
  '1500～1599万円',
  '役員クラス',
  '大阪府',
  '鉄鋼・非鉄金属',
  '経営(役員・CxO）/経営企画',
  '経営企画・戦略',
  '3回（4社経験）'],
 ['140038',
  '2026-06-01',
  '1',
  '2026/06/03',
  '0',
  'yahoo / paidsearch',
  'y01_brand_single',
  '1361',
  '(not set)',
  '54',
  '600～699万円',
  '社長・会長クラス',
  '神奈川県',
  '不動産',
  '経営(役員・CxO）/経営企画',
  '経営者・CEO・COO等',
  '3回（4社経験）'],
 ['140039',
  '2026-06-01',
  '1',
  '2026/06/02',
  '1',
  'yahoo / display',
  'y01_rtg',
  '409',
  '(not set)',
  '54',
  '2000～2999万円',
  '役員クラス',
  '東京都',
  'IT・通信',
  '経営(役員・CxO）/経営企画',
  'その他会社経営に携わる職種',
  '5回（6社経験）'],
 ['140040',
  '2026-06-01',
  '',
  '',
  '',
  '(not set)',
  '(not set)',
  '(not set)',
  '(not set)',
  '60',
  '1000～1099万円',
  '主任・主査クラス',
  '神奈川県',
  'IT・通信',
  'マーケティング・広報関連職',
  '販売促進',
  '転職経験なし'],
 ['140041',
  '2026-06-01',
  '1',
  '2026/06/02',
  '1',
  'raysus-inc.jp / referral',
  '(referral)',
  '(not set)',
  '(not set)',
  '60',
  '3000～3999万円',
  '役員クラス',
  '愛知県',
  '自動車',
  '経営(役員・CxO）/経営企画',
  '経営企画・戦略',
  '転職経験なし'],
 ['140042',
  '2026-06-01',
  '1',
  '2026/06/02',
  '1',
  'yahoo / display',
  'y05_income',
  '423',
  '(not set)',
  '50',
  '1900～1999万円',
  '部長クラス',
  '神奈川県',
  'コンサルティング',
  'コンサルタント',
  '戦略コンサルタント',
  '2回（3社経験）'],
 ['140043',
  '2026-06-01',
  '1',
  '2026/06/02',
  '1',
  '',
  '',
  '',
  '',
  '41',
  '900～999万円',
  '役員クラス',
  '東京都',
  '建設（建築・土木）',
  '建設・土木・設備工事関連職',
  '施工管理',
  '1回（2社経験）'],
 ['140044',
  '2026-06-02',
  '1',
  '2026/06/02',
  '1',
  'facebook / display',
  'CP02',
  'ADS05',
  '(not set)',
  '52',
  '900～999万円',
  '部長クラス',
  '東京都',
  'コンサルティング',
  'コンサルタント',
  'その他コンサルタント',
  '2回（3社経験）'],
 ['140045',
  '2026-06-02',
  '1',
  '2026/06/02',
  '1',
  'yahoo / display',
  'y05_income',
  '429',
  '(not set)',
  '52',
  '1200～1299万円',
  '部長クラス',
  '栃木県',
  'その他',
  'その他',
  'その他',
  '4回（5社経験）'],
 ['140046',
  '2026-06-02',
  '',
  '',
  '',
  '(not set)',
  '(not set)',
  '(not set)',
  '(not set)',
  '66',
  '1400～1499万円',
  '社長・会長クラス',
  '神奈川県',
  '商社',
  '経営(役員・CxO）/経営企画',
  '経営者・CEO・COO等',
  '1回（2社経験）'],
 ['140047',
  '2026-06-02',
  '1',
  '2026/06/03',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'shot_over2y',
  '(not set)',
  '(not set)',
  '50',
  '1600～1699万円',
  '部長クラス',
  '海外',
  '鉄鋼・非鉄金属',
  '経営(役員・CxO）/経営企画',
  '経営者・CEO・COO等',
  '1回（2社経験）'],
 ['140048',
  '2026-06-02',
  '1',
  '2026/06/03',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'shot_over1y',
  '(not set)',
  '(not set)',
  '63',
  '900～999万円',
  '部長クラス',
  '神奈川県',
  'その他',
  '建設・土木・設備工事関連職',
  'その他建築・土木関連職',
  '1回（2社経験）'],
 ['140049',
  '2026-06-02',
  '1',
  '2026/06/03',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'main1',
  '(not set)',
  '(not set)',
  '52',
  '1400～1499万円',
  '部長クラス',
  '東京都',
  '金融',
  '管理部門',
  '管理部長',
  '2回（3社経験）'],
 ['140050',
  '2026-06-02',
  '1',
  '2026/06/03',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'shot_over2y',
  '(not set)',
  '(not set)',
  '65',
  '3000～3999万円',
  '役員クラス',
  '東京都',
  '化学・石油',
  '経営(役員・CxO）/経営企画',
  'その他会社経営に携わる職種',
  '転職経験なし'],
 ['140051',
  '2026-06-02',
  '1',
  '2026/06/03',
  '1',
  'zeals_ad / chat_cpf',
  'RM',
  '(not set)',
  '(not set)',
  '57',
  '1100～1199万円',
  '部長クラス',
  '神奈川県',
  '金融',
  '営業',
  '代理店管理・渉外',
  '転職経験なし'],
 ['140052',
  '2026-06-02',
  '1',
  '2026/06/03',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'shot_181-365',
  '(not set)',
  '(not set)',
  '48',
  '1300～1399万円',
  '部長クラス',
  '大阪府',
  'その他',
  'その他',
  'その他',
  '2回（3社経験）'],
 ['140053',
  '2026-06-03',
  '',
  '',
  '',
  'zeals_ad / chat_cpf',
  'RM',
  '(not set)',
  '(not set)',
  '47',
  '1200～1299万円',
  '部長クラス',
  '東京都',
  '不動産',
  '管理部門',
  '法務・コンプライアンス',
  '5回（6社経験）'],
 ['140054',
  '2026-06-03',
  '',
  '',
  '',
  '(direct) / (none)',
  '(direct)',
  '(not set)',
  '(not set)',
  '64',
  '400～499万円',
  '役職なし',
  '鹿児島県',
  '建設（建築・土木）',
  '管理部門',
  'その他事務・管理',
  '6回（7社経験）'],
 ['140055',
  '2026-06-03',
  '1',
  '2026/06/09',
  '0',
  'zeals_ad,zeals / chat_cpf',
  'shot_over1y',
  '(not set)',
  '(not set)',
  '67',
  '3000～3999万円',
  '社長・会長クラス',
  '愛知県',
  '建設（建築・土木）',
  '経営(役員・CxO）/経営企画',
  '経営者・CEO・COO等',
  '1回（2社経験）'],
 ['140056',
  '2026-06-03',
  '',
  '',
  '',
  'zeals_ad,zeals / chat_cpf',
  'shot_over3y',
  '(not set)',
  '(not set)',
  '44',
  '1200～1299万円',
  'リーダークラス',
  '島根県',
  '金融',
  '営業',
  '営業・企画営業（法人対象）',
  '3回（4社経験）'],
 ['140057',
  '2026-06-03',
  '1',
  '2026/06/03',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'shot_181-365',
  '(not set)',
  '(not set)',
  '61',
  '1500～1599万円',
  '部長クラス',
  '東京都',
  '電子部品・半導体',
  '経営(役員・CxO）/経営企画',
  'M&A・合併・提携',
  '2回（3社経験）'],
 ['140058',
  '2026-06-03',
  '1',
  '2026/06/09',
  '0',
  'zeals_ad,zeals / chat_cpf',
  'main1',
  '(not set)',
  '(not set)',
  '61',
  '1300～1399万円',
  '部長クラス',
  '埼玉県',
  '医薬品',
  '製造・技術・研究開発関連職',
  '品質保証',
  '7回（8社経験）'],
 ['140059',
  '2026-06-03',
  '',
  '',
  '',
  'zeals_ad,zeals / chat_cpf',
  'main1',
  '(not set)',
  '(not set)',
  '56',
  '2000～2999万円',
  '部長クラス',
  '埼玉県',
  'IT・通信',
  '営業',
  '営業・企画営業（法人対象）',
  '7回（8社経験）'],
 ['140060',
  '2026-06-03',
  '',
  '',
  '',
  'zeals_ad,zeals / chat_cpf',
  'shot_over1y',
  '(not set)',
  '(not set)',
  '58',
  '1400～1499万円',
  '役職なし',
  '千葉県',
  '金融',
  '管理部門',
  '法務・コンプライアンス',
  '転職経験なし'],
 ['140061',
  '2026-06-03',
  '',
  '',
  '',
  'zeals_ad,zeals / chat_cpf',
  'main1',
  '(not set)',
  '(not set)',
  '56',
  '400～499万円',
  '個人事業主',
  '大阪府',
  '自動車',
  'その他',
  'その他',
  '4回（5社経験）'],
 ['140062',
  '2026-06-03',
  '1',
  '2026/06/04',
  '1',
  'yahoo / display',
  'y05_income',
  '423',
  '(not set)',
  '56',
  '1600～1699万円',
  '課長クラス',
  '愛知県',
  '自動車',
  'マーケティング・広報関連職',
  'ブランドマネージャー',
  '転職経験なし'],
 ['140063',
  '2026-06-03',
  '',
  '',
  '送信NG',
  '',
  '',
  '',
  '',
  '64',
  '700～799万円',
  '課長クラス',
  None,
  None,
  None,
  None,
  None],
 ['140064',
  '2026-06-03',
  '1',
  '2026/06/04',
  '1',
  '(not set)',
  '(not set)',
  '(not set)',
  '(not set)',
  '58',
  '1500～1599万円',
  '部長クラス',
  '京都府',
  '電子部品・半導体',
  'IT・WEB・メディア関連職',
  'その他IT関連職',
  '転職経験なし'],
 ['140065',
  '2026-06-03',
  '1',
  '2026/06/04',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'shot_over1y',
  '(not set)',
  '(not set)',
  '49',
  '1400～1499万円',
  '部長クラス',
  '東京都',
  '広告・メディア',
  '営業',
  '営業・企画営業（法人対象）',
  '転職経験なし'],
 ['140066',
  '2026-06-03',
  '',
  '',
  '',
  'zeals_ad,zeals / chat_cpf',
  'shot_91-180',
  '(not set)',
  '(not set)',
  '68',
  '1200～1299万円',
  '役員クラス',
  '神奈川県',
  '日用品・化粧品',
  '経営(役員・CxO）/経営企画',
  '経営企画・戦略',
  '2回（3社経験）'],
 ['140067',
  '2026-06-03',
  '1',
  '2026/06/04',
  '1',
  'facebook / display',
  'CP02',
  'ADS05',
  '(not set)',
  '54',
  '1000～1099万円',
  '課長クラス',
  '東京都',
  '小売・流通',
  'その他',
  'その他',
  '転職経験なし'],
 ['140068',
  '2026-06-03',
  '1',
  '2026/06/04',
  '1',
  'zeals_ad / chat_cpf',
  'RM',
  '(not set)',
  '(not set)',
  '53',
  '1300～1399万円',
  '課長クラス',
  '東京都',
  '金融',
  '管理部門',
  'その他事務・管理',
  '1回（2社経験）'],
 ['140069',
  '2026-06-03',
  '',
  '',
  '',
  'zeals_ad,zeals / chat_cpf',
  'shot_25-90',
  '(not set)',
  '(not set)',
  '58',
  '700～799万円',
  '役職なし',
  '東京都',
  '金融',
  '管理部門',
  'その他事務・管理',
  '転職経験なし'],
 ['140070',
  '2026-06-03',
  '',
  '',
  '',
  '(direct) / (none)',
  '(direct)',
  '(not set)',
  '(not set)',
  '61',
  '1200～1299万円',
  '役職なし',
  '千葉県',
  'IT・通信',
  '管理部門',
  '内部監査',
  '転職経験なし'],
 ['140071',
  '2026-06-03',
  '1',
  '2026/06/04',
  '1',
  'yahoo / display',
  'y05_income',
  '431',
  '(not set)',
  '64',
  '1600～1699万円',
  '役員クラス',
  '千葉県',
  '金融',
  '経営(役員・CxO）/経営企画',
  '経営者・CEO・COO等',
  '2回（3社経験）'],
 ['140072',
  '2026-06-03',
  '1',
  '2026/06/04',
  '1',
  'google / organic',
  '(organic)',
  '(not set)',
  '(not set)',
  '52',
  '1300～1399万円',
  '部長クラス',
  '埼玉県',
  '建設（建築・土木）',
  '営業',
  '営業・企画営業（法人対象）',
  '転職経験なし'],
 ['140073',
  '2026-06-03',
  '',
  '',
  '',
  'yahoo / display',
  'y05_income',
  '427',
  '(not set)',
  '51',
  '1700～1799万円',
  '部長クラス',
  '東京都',
  '自動車',
  '営業',
  '営業・企画営業（個人対象）',
  '7回（8社経験）'],
 ['140074',
  '2026-06-03',
  '',
  '',
  '',
  'yahoo / display',
  'y05_income',
  '423',
  '(not set)',
  '60',
  '800～899万円',
  '部長クラス',
  '山梨県',
  'その他',
  '管理部門',
  '管理部長',
  '3回（4社経験）'],
 ['140075',
  '2026-06-03',
  '',
  '',
  '',
  'zeals_ad,zeals / chat_cpf',
  'track_2',
  '(not set)',
  '(not set)',
  '65',
  '800～899万円',
  '役職なし',
  '東京都',
  '小売・流通',
  '営業',
  '営業・企画営業（法人対象）',
  '1回（2社経験）'],
 ['140076',
  '2026-06-03',
  '1',
  '2026/06/04',
  '1',
  'facebook / display',
  'CP02',
  'ADS05',
  '(not set)',
  '60',
  '1600～1699万円',
  '役員クラス',
  '東京都',
  'サービス',
  '経営(役員・CxO）/経営企画',
  '経営者・CEO・COO等',
  '転職経験なし'],
 ['140077',
  '2026-06-03',
  '1',
  '2026/06/04',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'main1',
  '(not set)',
  '(not set)',
  '55',
  '700～799万円',
  '部長クラス',
  '静岡県',
  '広告・メディア',
  '営業',
  '営業・企画営業（法人対象）',
  '転職経験なし'],
 ['140078',
  '2026-06-03',
  '',
  '',
  '',
  'zeals_ad,zeals / chat_cpf',
  'shot_over1y',
  '(not set)',
  '(not set)',
  '68',
  '1000～1099万円',
  'リーダークラス',
  '東京都',
  '小売・流通',
  '営業',
  '営業・企画営業（法人対象）',
  '3回（4社経験）'],
 ['140079',
  '2026-06-03',
  '1',
  '2026/06/04',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'main1',
  '(not set)',
  '(not set)',
  '58',
  '2000～2999万円',
  '役員クラス',
  '大阪府',
  'その他',
  'IT・WEB・メディア関連職',
  'プロダクトマネージャー',
  '転職経験なし'],
 ['140080',
  '2026-06-03',
  '1',
  '2026/06/04',
  '1',
  '(not set)',
  '(not set)',
  '(not set)',
  '(not set)',
  '61',
  '1900～1999万円',
  '部長クラス',
  '神奈川県',
  '電機・精密機械',
  '営業',
  '営業・企画営業（法人対象）',
  '2回（3社経験）'],
 ['140081',
  '2026-06-03',
  '1',
  '2026/06/04',
  '1',
  'google / organic',
  '(organic)',
  '(not set)',
  '(not set)',
  '56',
  '1000～1099万円',
  '課長クラス',
  '東京都',
  '金融',
  '金融関連職',
  'その他金融関連職',
  '転職経験なし'],
 ['140082',
  '2026-06-04',
  '',
  '',
  '',
  'yahoo / display',
  'y01_rtg',
  '414',
  '(not set)',
  '63',
  '1900～1999万円',
  '社長・会長クラス',
  '東京都',
  'IT・通信',
  '経営(役員・CxO）/経営企画',
  '新規事業企画',
  '10回以上（11社以上経験）'],
 ['140083',
  '2026-06-04',
  '1',
  '2026/06/04',
  '1',
  '(direct) / (none)',
  '(direct)',
  '(not set)',
  '(not set)',
  '56',
  '900～999万円',
  '部長クラス',
  '長野県',
  '不動産',
  '不動産関連職',
  'プロパティマネジメント',
  '1回（2社経験）'],
 ['140084',
  '2026-06-04',
  '',
  '',
  '',
  'yahoo / display',
  'y05_income',
  '427',
  '(not set)',
  '63',
  '600～699万円',
  '部長クラス',
  '兵庫県',
  '食品',
  '管理部門',
  '人事・労務',
  '2回（3社経験）'],
 ['140085',
  '2026-06-04',
  '1',
  '2026/06/04',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'main1',
  '(not set)',
  '(not set)',
  '61',
  '800～899万円',
  '課長クラス',
  '千葉県',
  'その他',
  'その他',
  'その他',
  '1回（2社経験）'],
 ['140086',
  '2026-06-04',
  '',
  '',
  '',
  'yahoo / display',
  'y05_income',
  '431',
  '(not set)',
  '66',
  '1200～1299万円',
  '役員クラス',
  '神奈川県',
  'サービス',
  '営業',
  '営業・企画営業（法人対象）',
  '1回（2社経験）'],
 ['140087',
  '2026-06-04',
  '1',
  '2026/06/04',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'shot_25-90',
  '(not set)',
  '(not set)',
  '64',
  '1200～1299万円',
  '部長クラス',
  '東京都',
  'その他',
  '営業',
  '営業・企画営業（法人対象）',
  '2回（3社経験）'],
 ['140088',
  '2026-06-04',
  '',
  '',
  '',
  'google / cpc',
  'G検索_01_指名',
  '(not set)',
  '転機',
  '52',
  '600～699万円',
  '課長クラス',
  '福岡県',
  'IT・通信',
  '管理部門',
  '人事・労務',
  '7回（8社経験）'],
 ['140089',
  '2026-06-04',
  '',
  '',
  '',
  'zeals_ad,zeals / chat_cpf',
  'shot_25-90',
  '(not set)',
  '(not set)',
  '65',
  '900～999万円',
  '顧問',
  '埼玉県',
  '食品',
  '営業',
  '営業・企画営業（法人対象）',
  '3回（4社経験）'],
 ['140090',
  '2026-06-04',
  '1',
  '2026/06/04',
  '1',
  '(direct) / (none)',
  '(direct)',
  '(not set)',
  '(not set)',
  '54',
  '1300～1399万円',
  '部長クラス',
  '埼玉県',
  '商社',
  '営業',
  '営業・企画営業（法人個人問わず海外営業）',
  '2回（3社経験）'],
 ['140091',
  '2026-06-04',
  '1',
  '2026/06/05',
  '1',
  'yahoo / display',
  'y05_income',
  '431',
  '(not set)',
  '52',
  '1300～1399万円',
  '部長クラス',
  '東京都',
  'IT・通信',
  '営業',
  'セールスエンジニア',
  '転職経験なし'],
 ['140092',
  '2026-06-04',
  '1',
  '2026/06/05',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'shot_91-180',
  '(not set)',
  '(not set)',
  '58',
  '1300～1399万円',
  '部長クラス',
  '東京都',
  'コンサルティング',
  'コンサルタント',
  '戦略コンサルタント',
  '3回（4社経験）'],
 ['140093',
  '2026-06-04',
  '',
  '',
  '',
  'yahoo / display',
  'y05_income',
  '423',
  '(not set)',
  '67',
  '800～899万円',
  '課長クラス',
  '大阪府',
  'その他',
  'コンサルタント',
  'パッケージ導入コンサルタント',
  '2回（3社経験）'],
 ['140094',
  '2026-06-04',
  '1',
  '2026/06/05',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'main1',
  '(not set)',
  '(not set)',
  '59',
  '3000～3999万円',
  '部長クラス',
  '東京都',
  '商社',
  '管理部門',
  '財務',
  '転職経験なし'],
 ['140095',
  '2026-06-04',
  '1',
  '2026/06/05',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'track_2',
  '(not set)',
  '(not set)',
  '51',
  '1300～1399万円',
  '部長クラス',
  '千葉県',
  'コンサルティング',
  'その他',
  'その他',
  '4回（5社経験）'],
 ['140096',
  '2026-06-04',
  '1',
  '2026/06/05',
  '1',
  'google / cpc',
  'G検索_01_指名',
  '(not set)',
  '転機',
  '54',
  '800～899万円',
  '部長クラス',
  '東京都',
  '不動産',
  '不動産関連職',
  'その他不動産関連職',
  '4回（5社経験）'],
 ['140097',
  '2026-06-04',
  '1',
  '2026/06/08',
  '0',
  '',
  '',
  '',
  '',
  '56',
  '500～599万円',
  '課長クラス',
  '沖縄県',
  '小売・流通',
  '製造・技術・研究開発関連職',
  'その他研究・開発',
  '4回（5社経験）'],
 ['140098',
  '2026-06-04',
  '1',
  '2026/06/09',
  '1',
  'google / cpc',
  'G検索_01_指名',
  '(not set)',
  '転機',
  '62',
  '1400～1499万円',
  '役員クラス',
  '福岡県',
  'IT・通信',
  '営業',
  '営業・企画営業（法人対象）',
  '転職経験なし'],
 ['140099',
  '2026-06-04',
  '',
  '',
  '',
  'zeals_ad,zeals / chat_cpf',
  'track_5',
  '(not set)',
  '(not set)',
  '62',
  '600～699万円',
  '部長クラス',
  '滋賀県',
  'コンサルティング',
  '製造・技術・研究開発関連職',
  '研究開発（処方開発）',
  '4回（5社経験）'],
 ['140100',
  '2026-06-04',
  '1',
  '2026/06/05',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'shot_over1y',
  '(not set)',
  '(not set)',
  '55',
  '2000～2999万円',
  'リーダークラス',
  '東京都',
  '電機・精密機械',
  '営業',
  '営業・企画営業（法人対象）',
  '転職経験なし'],
 ['140101',
  '2026-06-04',
  '1',
  '2026/06/05',
  '1',
  '',
  '',
  '',
  '',
  '54',
  '1200～1299万円',
  '部長クラス',
  '東京都',
  '金融',
  '金融関連職',
  'その他金融関連職',
  '転職経験なし'],
 ['140102',
  '2026-06-05',
  '1',
  '2026/06/05',
  '1',
  '',
  '',
  '',
  '',
  '60',
  '1100～1199万円',
  '部長クラス',
  '岐阜県',
  'その他機械',
  'その他',
  'その他',
  '1回（2社経験）'],
 ['140103',
  '2026-06-05',
  '1',
  '2026/06/05',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'main1',
  '(not set)',
  '(not set)',
  '59',
  '1100～1199万円',
  '部長クラス',
  '大阪府',
  '商社',
  '管理部門',
  '物流企画・ロジスティクス',
  '2回（3社経験）'],
 ['140104',
  '2026-06-05',
  '1',
  '2026/06/05',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'shot_25-90',
  '(not set)',
  '(not set)',
  '53',
  '1300～1399万円',
  '部長クラス',
  '東京都',
  '商社',
  '営業',
  '営業・企画営業（法人対象）',
  '転職経験なし'],
 ['140105',
  '2026-06-05',
  '1',
  '2026/06/05',
  '1',
  'zeals_ad / chat_cpf',
  'RM',
  '(not set)',
  '(not set)',
  '57',
  '1000～1099万円',
  '部長クラス',
  '大阪府',
  '運輸・倉庫',
  '管理部門',
  '総務',
  '2回（3社経験）'],
 ['140106',
  '2026-06-05',
  '',
  '',
  '',
  'google / organic',
  '(organic)',
  '(not set)',
  '(not set)',
  '55',
  '900～999万円',
  '役職なし',
  '埼玉県',
  '電機・精密機械',
  '営業',
  '営業・企画営業（法人対象）',
  '4回（5社経験）'],
 ['140107',
  '2026-06-05',
  '',
  '',
  '',
  'facebook / display',
  'CP02',
  'ADS05',
  '(not set)',
  '64',
  '400～499万円',
  '顧問',
  '愛知県',
  'サービス',
  '管理部門',
  '総務',
  '5回（6社経験）'],
 ['140108',
  '2026-06-05',
  '1',
  '2026/06/08',
  '0',
  'yahoo / display',
  'y01_rtg',
  '420',
  '(not set)',
  '37',
  '1100～1199万円',
  '課長クラス',
  '神奈川県',
  'コンサルティング',
  'コンサルタント',
  'その他コンサルタント',
  '1回（2社経験）'],
 ['140109',
  '2026-06-05',
  '1',
  '2026/06/08',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'shot_91-180',
  '(not set)',
  '(not set)',
  '58',
  '800～899万円',
  '顧問',
  '東京都',
  '繊維・アパレル',
  'マーケティング・広報関連職',
  'ブランドマネージャー',
  '2回（3社経験）'],
 ['140110',
  '2026-06-05',
  '',
  '',
  '',
  'yahoo / display',
  'y05_income',
  '423',
  '(not set)',
  '51',
  '600～699万円',
  'リーダークラス',
  '神奈川県',
  'その他',
  '営業',
  'その他営業職',
  '2回（3社経験）'],
 ['140111',
  '2026-06-05',
  '1',
  '2026/06/08',
  '1',
  'zeals_ad,zeals / chat_cpf',
  'shot_91-180',
  '(not set)',
  '(not set)',
  '57',
  '1100～1199万円',
  '課長クラス',
  '徳島県',
  '金融',
  '管理部門',
  'センター・倉庫管理・運行・配車管理',
  '転職経験なし'],
 ['140112',
  '2026-06-05',
  '',
  '2026/06/08',
  '送信NG',
  '(direct) / (none)',
  '(direct)',
  '(not set)',
  '(not set)',
  '64',
  '800～899万円',
  '部長クラス',
  '岐阜県',
  '運輸・倉庫',
  '管理部門',
  '内部監査',
  '転職経験なし'],
 ['140113',
  '2026-06-06',
  '',
  '',
  '送信NG',
  'google / cpc',
  'G検索_01_指名',
  '(not set)',
  '転機 転職',
  '2025',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1'],
 ['140114',
  '2026-06-06',
  '',
  '',
  '',
  'facebookcasm / display',
  'CP02',
  'ADS09',
  '(not set)',
  '58',
  '700～799万円',
  '主任・主査クラス',
  '神奈川県',
  '金融',
  '金融関連職',
  'その他金融関連職',
  '転職経験なし'],
 ['140115',
  '2026-06-06',
  '1',
  '2026/06/08',
  '1',
  '(not set)',
  '(not set)',
  '(not set)',
  '(not set)',
  '55',
  '1100～1199万円',
  '部長クラス',
  '埼玉県',
  '金融',
  '金融関連職',
  'その他金融関連職',
  '転職経験なし'],
 ['140116',
  '2026-06-06',
  '',
  '',
  '',
  'zeals_ad,zeals / chat_cpf',
  'shot_over2y',
  '(not set)',
  '(not set)',
  '57',
  '500～599万円',
  '部長クラス',
  '大阪府',
  'サービス',
  '営業',
  '営業・企画営業（法人対象）',
  '2回（3社経験）'],
 ['140117',
  '2026-06-06',
  '',
  '',
  '',
  'yahoo / paidsearch',
  'y01_brand_single',
  '1361',
  '(not set)',
  '55',
  '900～999万円',
  '部長クラス',
  '東京都',
  'IT・通信',
  'コンサルタント',
  'システムコンサルタント',
  '4回（5社経験）'],
 ['140118',
  '2026-06-06',
  '1',
  '2026/06/08',
  '1',
  'yahoo / organic',
  '(organic)',
  '(not set)',
  '(not set)',
  '64',
  '700～799万円',
  '部長クラス',
  '岐阜県',
  '運輸・倉庫',
  '管理部門',
  '内部監査',
  '転職経験なし'],
 ['140119',
  '2026-06-06',
  '',
  '',
  '',
  '(not set)',
  '(not set)',
  '(not set)',
  '(not set)',
  '52',
  '1400～1499万円',
  '部長クラス',
  '埼玉県',
  'その他',
  'その他',
  'その他',
  '7回（8社経験）'],
 ['140120',
  '2026-06-06',
  '1',
  '2026/06/08',
  '1',
  'yahoo / display',
  'y05_income',
  '431',
  '(not set)',
  '49',
  '1200～1299万円',
  '部長クラス',
  '群馬県',
  'その他',
  '医療・介護福祉関連職',
  'その他医療・介護福祉関連職',
  '2回（3社経験）'],
 ['140121',
  '2026-06-06',
  '',
  '',
  '',
  'bing / organic',
  '(organic)',
  '(not set)',
  '(not set)',
  '54',
  '1000～1099万円',
  '役員クラス',
  '奈良県',
  '食品',
  '経営(役員・CxO）/経営企画',
  'CFO',
  '4回（5社経験）'],
 ['140122',
  '2026-06-06',
  '',
  '',
  '',
  'yahoo / display',
  'y01_rtg',
  '413',
  '(not set)',
  '66',
  '600～699万円',
  '部長クラス',
  '神奈川県',
  '不動産',
  '管理部門',
  '経理',
  '9回（10社経験）'],
 ['140123',
  '2026-06-06',
  '1',
  '2026/06/08',
  '1',
  'yahoo / display',
  'y05_income',
  '431',
  '(not set)',
  '62',
  '800～899万円',
  '役員クラス',
  '千葉県',
  'その他',
  '経営(役員・CxO）/経営企画',
  'その他会社経営に携わる職種',
  '1回（2社経験）'],
 ['140124',
  '2026-06-06',
  '1',
  '2026/06/08',
  '1',
  'facebook / display',
  'CP02',
  'ADS05',
  '(not set)',
  '56',
  '1100～1199万円',
  '部長クラス',
  '神奈川県',
  'その他',
  '管理部門',
  '経理',
  '転職経験なし'],
 ['140125',

In [299]:
# 認証の準備
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly',
          'https://www.googleapis.com/auth/spreadsheets']
json_path = r"Z:\Users\suehara\Documents\python\analysis\python_ss\credentials.json"
service = ps.get_auth(SCOPES, json_path)


# NMシートへの書き込み処理
if len(matching_index_NM) > 0:
    SPREADSHEET_ID_NM = '1YRjsfJ76yfAnhoyTlsvcXVKZhmmcvkNwpApf9iubByc'
    Sheet_NAME = 'サマリー!A'
    Sheet_row = str(matching_index_NM[0] + 1)
    RANGE_NAME = Sheet_NAME + Sheet_row
    ps.update_ss(SPREADSHEET_ID_NM, RANGE_NAME, ALL_data, service)
    print("NMシートの更新が完了しました。")
else:
    print("スキップ: NMの条件に一致するデータが見つかりませんでした。")


# CAシートへの書き込み処理
if len(matching_index_CA) > 0:
    SPREADSHEET_ID_CA = '1fVbpOYwIRsbW69EDsbJlTJwJVPTexi8RoMd3ahiO-IA'
    Sheet_NAME = 'サマリー!A'
    Sheet_row = str(matching_index_CA[0] + 1)
    RANGE_NAME = Sheet_NAME + Sheet_row
    ps.update_ss(SPREADSHEET_ID_CA, RANGE_NAME, ALL_data, service)
    print("CAシートの更新が完了しました。")
else:
    print("スキップ: CAの条件に一致するデータが見つかりませんでした。")


# GAXシートへの書き込み処理
if len(matching_index_GAX) > 0:
    SPREADSHEET_ID_GAX = '1JxBS0dT8nR_o_ehqVdlKYx3iD1jEMIaQPXWl6wJIXJk'
    Sheet_NAME = '手上げデータ!A'
    Sheet_row = str(matching_index_GAX[0] + 1)
    RANGE_NAME = Sheet_NAME + Sheet_row
    ps.update_ss(SPREADSHEET_ID_GAX, RANGE_NAME, ALL_data, service)
    print("GAXシートの更新が完了しました。")
else:
    print("スキップ: GAXの条件に一致するデータが見つかりませんでした。")

スキップ: NMの条件に一致するデータが見つかりませんでした。
スキップ: CAの条件に一致するデータが見つかりませんでした。
スキップ: GAXの条件に一致するデータが見つかりませんでした。

## 媒体の広告を抽出する

In [300]:
adinfo.columns

Index(['tenki_id', '登録日時', 'フリ先', '手上げ日付', '本手上げ', 'KN共有日', '参照元/メディア',
       'キャンペーン', '広告ID', 'KWD', '', '年齢', '役職'],
      dtype='object')

In [301]:
adinfoB = adinfo.copy()
adinfoB = adinfoB[["tenki_id","登録日時","キャンペーン","広告ID"]]
adinfoB = adinfoB[adinfoB["キャンペーン"] == "nm_facebook"] 
adinfoB['登録日時'] = pd.to_datetime(adinfoB['登録日時'])
adinfoB = adinfoB[adinfoB['登録日時'] >= firstday_minus_60]
adinfoB['tenki_id'] = adinfoB['tenki_id'].astype('int64')

In [302]:
# データが1件以上あるか確認してから最初のIDを取り出す
if len(adinfoB) > 0:
    first_tenki_id = adinfoB['tenki_id'].iloc[0]
    print(first_tenki_id)
else:
    print("条件（キャンペーンや日付）に一致するデータが見つかりませんでした。")

条件（キャンペーンや日付）に一致するデータが見つかりませんでした。

In [303]:
#NMシートを取得
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly',
          'https://www.googleapis.com/auth/spreadsheets']
json_path = r"Z:\Users\suehara\Documents\python\analysis\python_ss\credentials.json"
service = ps.get_auth(SCOPES,json_path)
SPREADSHEET_ID_NM = '1YRjsfJ76yfAnhoyTlsvcXVKZhmmcvkNwpApf9iubByc'
Sheet_NAME = 'データセット1!A'
Sheet_row = ":B"
RANGE_NAME = Sheet_NAME+Sheet_row
recentID_NM = ps.get_ss(SPREADSHEET_ID_NM,RANGE_NAME,service)

In [304]:
recentID_NM.columns

Index(['広告のコンテンツ', 'ID'], dtype='object')

In [305]:
recentID_NM['ID'] = recentID_NM['ID'].astype('int64')

# adinfoB にデータが1件以上あるか確認します
if len(adinfoB) > 0:
    # データがある場合は、最初のtenki_idに一致するインデックスを取得します
    target_id = adinfoB['tenki_id'].iloc[0]
    matching_index_NM = recentID_NM[recentID_NM["ID"] == target_id].index
else:
    # データがない場合は、空のリストを作成しておきます
    matching_index_NM = []
    print("adinfoBに条件に一致するデータが存在しませんでした。")

adinfoBに条件に一致するデータが存在しませんでした。

In [306]:
adinfoB = adinfoB[["広告ID","tenki_id"]]

In [307]:
adinfoB

Empty DataFrame
Columns: [広告ID, tenki_id]
Index: []

In [308]:
adinfoB["tenki_id"] = adinfoB["tenki_id"].astype(str) 

adinfoB.replace([np.inf, -np.inf], np.nan, inplace=True)
adinfoB = adinfoB.values.tolist()

In [309]:
# matching_index_NM[0]+1

In [310]:
# #NMシートにコピペ
# SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly',
#           'https://www.googleapis.com/auth/spreadsheets']
# json_path = r"Z:\Users\suehara\Documents\python\analysis\python_ss\credentials.json"
# service = ps.get_auth(SCOPES,json_path)
# SPREADSHEET_ID_NM = '1YRjsfJ76yfAnhoyTlsvcXVKZhmmcvkNwpApf9iubByc'
# Sheet_NAME = 'データセット1!A'
# Sheet_row = str(matching_index_NM[0]+1)
# RANGE_NAME = Sheet_NAME+Sheet_row
# ps.update_ss(SPREADSHEET_ID_NM,RANGE_NAME,adinfoB,service)